/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TCbuffer
 * Methods emitted: 15 (bounded-state=10 · stateless=3 · io-meta=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTCbuffer {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTCbuffer() { /* utility */ }

    /**
     * MEOS {@code tcbuffer_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer tcbuffer_make(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_make(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_to_tfloat} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tcbuffer_to_tfloat(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_to_tfloat requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_to_tfloat(arg0);
    }

    /**
     * MEOS {@code tcbuffer_to_tgeompoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tcbuffer_to_tgeompoint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_to_tgeompoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_to_tgeompoint(arg0);
    }

    /**
     * MEOS {@code tcbuffer_at_cbuffer} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tcbuffer_at_cbuffer(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_at_cbuffer requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_at_cbuffer(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_at_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tcbuffer_at_geom(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_at_geom requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_at_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_at_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tcbuffer_at_stbox(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_at_stbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_at_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tcbuffer_expand} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tcbuffer_expand(jnr.ffi.Pointer arg0, double arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_expand requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_expand(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_minus_cbuffer} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tcbuffer_minus_cbuffer(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_minus_cbuffer requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_minus_cbuffer(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_minus_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tcbuffer_minus_geom(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_minus_geom requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_minus_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_minus_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tcbuffer_minus_stbox(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_minus_stbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_minus_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tcbuffer_points} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tcbuffer_points(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_points requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_points(arg0);
    }

    /**
     * MEOS {@code tcbuffer_radius} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tcbuffer_radius(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_radius requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_radius(arg0);
    }

    /**
     * MEOS {@code tcbuffer_from_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tcbuffer_from_mfjson(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_from_mfjson requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_from_mfjson(arg0);
    }

    /**
     * MEOS {@code tcbuffer_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tcbuffer_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_in(arg0);
    }

}
