/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: FloatSpanSet
 * Methods emitted: 13 (bounded-state=10 · io-meta=2 · stateless=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsFloatSpanSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsFloatSpanSet() { /* utility */ }

    /**
     * MEOS {@code floatspanset_to_intspanset} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer floatspanset_to_intspanset(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_to_intspanset requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_to_intspanset(arg0);
    }

    /**
     * MEOS {@code floatspanset_bins} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspanset_bins(jnr.ffi.Pointer arg0, double arg1, double arg2, jnr.ffi.Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_bins requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_bins(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code floatspanset_ceil} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspanset_ceil(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_ceil requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_ceil(arg0);
    }

    /**
     * MEOS {@code floatspanset_degrees} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspanset_degrees(jnr.ffi.Pointer arg0, boolean arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_degrees requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_degrees(arg0, arg1);
    }

    /**
     * MEOS {@code floatspanset_floor} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspanset_floor(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_floor requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_floor(arg0);
    }

    /**
     * MEOS {@code floatspanset_lower} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double floatspanset_lower(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_lower requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_lower(arg0);
    }

    /**
     * MEOS {@code floatspanset_radians} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspanset_radians(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_radians requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_radians(arg0);
    }

    /**
     * MEOS {@code floatspanset_round} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspanset_round(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_round requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_round(arg0, arg1);
    }

    /**
     * MEOS {@code floatspanset_shift_scale} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspanset_shift_scale(jnr.ffi.Pointer arg0, double arg1, double arg2, boolean arg3, boolean arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_shift_scale requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_shift_scale(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code floatspanset_upper} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double floatspanset_upper(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_upper requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_upper(arg0);
    }

    /**
     * MEOS {@code floatspanset_width} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double floatspanset_width(jnr.ffi.Pointer arg0, boolean arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_width requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_width(arg0, arg1);
    }

    /**
     * MEOS {@code floatspanset_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer floatspanset_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_in(arg0);
    }

    /**
     * MEOS {@code floatspanset_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String floatspanset_out(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspanset_out requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.floatspanset_out(arg0, arg1);
    }

}
