/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: STBox
 * Methods emitted: 54 (bounded-state=42 · io-meta=6 · stateless=6)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsSTBox {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsSTBox() { /* utility */ }

    /**
     * MEOS {@code stbox_copy} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer stbox_copy(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_copy requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_copy(arg0);
    }

    /**
     * MEOS {@code stbox_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer stbox_make(boolean arg0, boolean arg1, boolean arg2, int arg3, double arg4, double arg5, double arg6, double arg7, double arg8, double arg9, jnr.ffi.Pointer arg10) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_make(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }

    /**
     * MEOS {@code stbox_to_box3d} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer stbox_to_box3d(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_to_box3d requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_to_box3d(arg0);
    }

    /**
     * MEOS {@code stbox_to_gbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer stbox_to_gbox(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_to_gbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_to_gbox(arg0);
    }

    /**
     * MEOS {@code stbox_to_geo} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer stbox_to_geo(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_to_geo requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_to_geo(arg0);
    }

    /**
     * MEOS {@code stbox_to_tstzspan} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer stbox_to_tstzspan(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_to_tstzspan requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_to_tstzspan(arg0);
    }

    /**
     * MEOS {@code stbox_area} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double stbox_area(jnr.ffi.Pointer arg0, boolean arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_area requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_area(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_cmp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int stbox_cmp(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_cmp requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_eq} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean stbox_eq(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_eq requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_eq(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_expand_space} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_expand_space(jnr.ffi.Pointer arg0, double arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_expand_space requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_expand_space(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_expand_time} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_expand_time(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_expand_time requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_expand_time(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_ge} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean stbox_ge(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_ge requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_ge(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_get_space} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_get_space(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_get_space requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_get_space(arg0);
    }

    /**
     * MEOS {@code stbox_get_space_tile} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_get_space_tile(jnr.ffi.Pointer arg0, double arg1, double arg2, double arg3, jnr.ffi.Pointer arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_get_space_tile requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_get_space_tile(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code stbox_get_space_time_tile} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_get_space_time_tile(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1, double arg2, double arg3, double arg4, jnr.ffi.Pointer arg5, jnr.ffi.Pointer arg6, java.time.OffsetDateTime arg7) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_get_space_time_tile requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_get_space_time_tile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /**
     * MEOS {@code stbox_get_time_tile} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_get_time_tile(java.time.OffsetDateTime arg0, jnr.ffi.Pointer arg1, java.time.OffsetDateTime arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_get_time_tile requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_get_time_tile(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code stbox_gt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean stbox_gt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_gt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_gt(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_hash} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int stbox_hash(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_hash requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_hash(arg0);
    }

    /**
     * MEOS {@code stbox_hash_extended} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static long stbox_hash_extended(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_hash_extended requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_hash_extended(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_hast} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean stbox_hast(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_hast requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_hast(arg0);
    }

    /**
     * MEOS {@code stbox_hasx} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean stbox_hasx(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_hasx requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_hasx(arg0);
    }

    /**
     * MEOS {@code stbox_hasz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean stbox_hasz(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_hasz requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_hasz(arg0);
    }

    /**
     * MEOS {@code stbox_isgeodetic} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean stbox_isgeodetic(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_isgeodetic requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_isgeodetic(arg0);
    }

    /**
     * MEOS {@code stbox_le} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean stbox_le(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_le requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_le(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_lt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean stbox_lt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_lt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_lt(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_ne} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean stbox_ne(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_ne requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_ne(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_perimeter} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double stbox_perimeter(jnr.ffi.Pointer arg0, boolean arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_perimeter requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_perimeter(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_quad_split} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_quad_split(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_quad_split requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_quad_split(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_round} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_round(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_round requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_round(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_set_srid} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_set_srid(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_set_srid requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_set_srid(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_shift_scale_time} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_shift_scale_time(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_shift_scale_time requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_shift_scale_time(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code stbox_space_tiles} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_space_tiles(jnr.ffi.Pointer arg0, double arg1, double arg2, double arg3, jnr.ffi.Pointer arg4, boolean arg5, jnr.ffi.Pointer arg6) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_space_tiles requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_space_tiles(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
    }

    /**
     * MEOS {@code stbox_space_time_tiles} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_space_time_tiles(jnr.ffi.Pointer arg0, double arg1, double arg2, double arg3, jnr.ffi.Pointer arg4, jnr.ffi.Pointer arg5, java.time.OffsetDateTime arg6, boolean arg7, jnr.ffi.Pointer arg8) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_space_time_tiles requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_space_time_tiles(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /**
     * MEOS {@code stbox_srid} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int stbox_srid(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_srid requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_srid(arg0);
    }

    /**
     * MEOS {@code stbox_time_tiles} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_time_tiles(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, java.time.OffsetDateTime arg2, boolean arg3, jnr.ffi.Pointer arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_time_tiles requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_time_tiles(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code stbox_tmax} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_tmax(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_tmax requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_tmax(arg0);
    }

    /**
     * MEOS {@code stbox_tmax_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_tmax_inc(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_tmax_inc requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_tmax_inc(arg0);
    }

    /**
     * MEOS {@code stbox_tmin} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_tmin(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_tmin requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_tmin(arg0);
    }

    /**
     * MEOS {@code stbox_tmin_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_tmin_inc(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_tmin_inc requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_tmin_inc(arg0);
    }

    /**
     * MEOS {@code stbox_transform} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_transform(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_transform requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_transform(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_transform_pipeline} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_transform_pipeline(jnr.ffi.Pointer arg0, java.lang.String arg1, int arg2, boolean arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_transform_pipeline requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_transform_pipeline(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code stbox_volume} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double stbox_volume(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_volume requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_volume(arg0);
    }

    /**
     * MEOS {@code stbox_xmax} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_xmax(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_xmax requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_xmax(arg0);
    }

    /**
     * MEOS {@code stbox_xmin} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_xmin(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_xmin requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_xmin(arg0);
    }

    /**
     * MEOS {@code stbox_ymax} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_ymax(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_ymax requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_ymax(arg0);
    }

    /**
     * MEOS {@code stbox_ymin} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_ymin(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_ymin requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_ymin(arg0);
    }

    /**
     * MEOS {@code stbox_zmax} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_zmax(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_zmax requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_zmax(arg0);
    }

    /**
     * MEOS {@code stbox_zmin} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer stbox_zmin(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_zmin requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_zmin(arg0);
    }

    /**
     * MEOS {@code stbox_as_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String stbox_as_hexwkb(jnr.ffi.Pointer arg0, byte arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_as_hexwkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_as_hexwkb(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code stbox_as_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer stbox_as_wkb(jnr.ffi.Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_as_wkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_as_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_from_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer stbox_from_hexwkb(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_from_hexwkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_from_hexwkb(arg0);
    }

    /**
     * MEOS {@code stbox_from_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer stbox_from_wkb(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_from_wkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_from_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code stbox_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer stbox_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_in(arg0);
    }

    /**
     * MEOS {@code stbox_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String stbox_out(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "stbox_out requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.stbox_out(arg0, arg1);
    }

}
