/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by codegen_flink_free.py — do not edit by hand.
 * Source header: meos_npoint.h
 * Methods emitted: 82 (stateless=44 · bounded-state=11 · io-meta=10 · windowed=9 · cross-stream=8)
 * Scope: MEOS public functions NOT classified into any object-model class
 *        (free functions, not methods on a class).
 * Source: JMEOS PR #19 (functions.GeneratedFunctions) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsFreeNpoint {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsFreeNpoint() { /* utility */ }

    /**
     * MEOS {@code contained_npoint_set} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: topology/position rel on 2 scalars (box/span algebra)</p>
     */
    public static boolean contained_npoint_set(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "contained_npoint_set requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.contained_npoint_set(arg0, arg1);
    }

    /**
     * MEOS {@code contains_set_npoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: set/span/box algebra (pure)</p>
     */
    public static boolean contains_set_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "contains_set_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.contains_set_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code geom_to_nsegment} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: base-type fn, default pure</p>
     */
    public static jnr.ffi.Pointer geom_to_nsegment(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "geom_to_nsegment requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.geom_to_nsegment(arg0);
    }

    /**
     * MEOS {@code get_srid_ways} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static int get_srid_ways() {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "get_srid_ways requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.get_srid_ways();
    }

    /**
     * MEOS {@code intersection_set_npoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: set/span/box algebra (pure)</p>
     */
    public static jnr.ffi.Pointer intersection_set_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "intersection_set_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.intersection_set_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_cmp} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static int npoint_cmp(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_cmp requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_eq} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static boolean npoint_eq(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_eq requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_eq(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_ge} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static boolean npoint_ge(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_ge requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_ge(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_gt} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static boolean npoint_gt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_gt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_gt(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_hash} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static int npoint_hash(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_hash requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_hash(arg0);
    }

    /**
     * MEOS {@code npoint_hash_extended} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static int npoint_hash_extended(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_hash_extended requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_hash_extended(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_le} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static boolean npoint_le(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_le requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_le(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_lt} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static boolean npoint_lt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_lt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_lt(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: make/from_base of instant/scalar</p>
     */
    public static jnr.ffi.Pointer npoint_make(long arg0, double arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_make(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_ne} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar comparison/hash</p>
     */
    public static boolean npoint_ne(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_ne requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_ne(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_position} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: base-type fn, default pure</p>
     */
    public static double npoint_position(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_position requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_position(arg0);
    }

    /**
     * MEOS {@code npoint_round} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: transform/normalize (pure)</p>
     */
    public static jnr.ffi.Pointer npoint_round(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_round requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_round(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_route} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: base-type fn, default pure</p>
     */
    public static long npoint_route(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_route requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_route(arg0);
    }

    /**
     * MEOS {@code npoint_same} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: base-type fn, default pure</p>
     */
    public static boolean npoint_same(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_same requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_same(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_srid} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: base-type fn, default pure</p>
     */
    public static int npoint_srid(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_srid requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_srid(arg0);
    }

    /**
     * MEOS {@code npoint_timestamptz_to_stbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: name pattern is _to_<type></p>
     */
    public static jnr.ffi.Pointer npoint_timestamptz_to_stbox(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_timestamptz_to_stbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_timestamptz_to_stbox(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_to_geompoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: base-type fn, default pure</p>
     */
    public static jnr.ffi.Pointer npoint_to_geompoint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_to_geompoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_to_geompoint(arg0);
    }

    /**
     * MEOS {@code npoint_to_nsegment} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: base-type fn, default pure</p>
     */
    public static jnr.ffi.Pointer npoint_to_nsegment(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_to_nsegment requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_to_nsegment(arg0);
    }

    /**
     * MEOS {@code npoint_to_set} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: name pattern is _to_<type></p>
     */
    public static jnr.ffi.Pointer npoint_to_set(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_to_set requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_to_set(arg0);
    }

    /**
     * MEOS {@code npoint_to_stbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: name pattern is _to_<type></p>
     */
    public static jnr.ffi.Pointer npoint_to_stbox(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_to_stbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_to_stbox(arg0);
    }

    /**
     * MEOS {@code npoint_tstzspan_to_stbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: name pattern is _to_<type></p>
     */
    public static jnr.ffi.Pointer npoint_tstzspan_to_stbox(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_tstzspan_to_stbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_tstzspan_to_stbox(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_union_transfn} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: base-type fn, default pure</p>
     */
    public static jnr.ffi.Pointer npoint_union_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_union_transfn requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_union_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_cmp} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static int nsegment_cmp(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_cmp requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_eq} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static boolean nsegment_eq(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_eq requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_eq(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_ge} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static boolean nsegment_ge(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_ge requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_ge(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_gt} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static boolean nsegment_gt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_gt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_gt(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_le} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static boolean nsegment_le(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_le requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_le(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_lt} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static boolean nsegment_lt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_lt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_lt(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: make/from_base of instant/scalar</p>
     */
    public static jnr.ffi.Pointer nsegment_make(long arg0, double arg1, double arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_make(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code nsegment_ne} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static boolean nsegment_ne(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_ne requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_ne(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_round} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: transform/normalize (pure)</p>
     */
    public static jnr.ffi.Pointer nsegment_round(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_round requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_round(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_route} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static long nsegment_route(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_route requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_route(arg0);
    }

    /**
     * MEOS {@code nsegment_srid} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static int nsegment_srid(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_srid requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_srid(arg0);
    }

    /**
     * MEOS {@code nsegment_to_geom} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: name pattern is _to_<type></p>
     */
    public static jnr.ffi.Pointer nsegment_to_geom(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_to_geom requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_to_geom(arg0);
    }

    /**
     * MEOS {@code nsegment_to_stbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: name pattern is _to_<type></p>
     */
    public static jnr.ffi.Pointer nsegment_to_stbox(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_to_stbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_to_stbox(arg0);
    }

    /**
     * MEOS {@code route_exists} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: scalar in/out (default-stateless catch-all)</p>
     */
    public static boolean route_exists(long arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "route_exists requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.route_exists(arg0);
    }

    /**
     * MEOS {@code teq_tnpoint_npoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: temporal comparison (per-instant)</p>
     */
    public static jnr.ffi.Pointer teq_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "teq_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.teq_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code tne_tnpoint_npoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: temporal comparison (per-instant)</p>
     */
    public static jnr.ffi.Pointer tne_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tne_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tne_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code union_set_npoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Free function (not class-classified). Classification rule: set/span/box algebra (pure)</p>
     */
    public static jnr.ffi.Pointer union_set_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "union_set_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.union_set_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code minus_npoint_set} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: restriction name pattern</p>
     */
    public static jnr.ffi.Pointer minus_npoint_set(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "minus_npoint_set requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.minus_npoint_set(arg0, arg1);
    }

    /**
     * MEOS {@code minus_set_npoint} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: restriction name pattern</p>
     */
    public static jnr.ffi.Pointer minus_set_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "minus_set_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.minus_set_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code nad_tnpoint_geo} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: distance op</p>
     */
    public static double nad_tnpoint_geo(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nad_tnpoint_geo requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nad_tnpoint_geo(arg0, arg1);
    }

    /**
     * MEOS {@code nad_tnpoint_npoint} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: distance op</p>
     */
    public static double nad_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nad_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nad_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code nad_tnpoint_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: distance op</p>
     */
    public static double nad_tnpoint_stbox(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nad_tnpoint_stbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nad_tnpoint_stbox(arg0, arg1);
    }

    /**
     * MEOS {@code nai_tnpoint_geo} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: distance op</p>
     */
    public static jnr.ffi.Pointer nai_tnpoint_geo(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nai_tnpoint_geo requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nai_tnpoint_geo(arg0, arg1);
    }

    /**
     * MEOS {@code nai_tnpoint_npoint} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: distance op</p>
     */
    public static jnr.ffi.Pointer nai_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nai_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nai_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code shortestline_tnpoint_geo} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: distance op</p>
     */
    public static jnr.ffi.Pointer shortestline_tnpoint_geo(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "shortestline_tnpoint_geo requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.shortestline_tnpoint_geo(arg0, arg1);
    }

    /**
     * MEOS {@code shortestline_tnpoint_npoint} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: distance op</p>
     */
    public static jnr.ffi.Pointer shortestline_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "shortestline_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.shortestline_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code tdistance_tnpoint_npoint} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Free function (not class-classified). Classification rule: distance op</p>
     */
    public static jnr.ffi.Pointer tdistance_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tdistance_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tdistance_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code always_eq_npoint_tnpoint} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 1 temporal</p>
     */
    public static int always_eq_npoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_eq_npoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_eq_npoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code always_eq_tnpoint_npoint} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 1 temporal</p>
     */
    public static int always_eq_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_eq_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_eq_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code always_ne_npoint_tnpoint} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 1 temporal</p>
     */
    public static int always_ne_npoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_ne_npoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_ne_npoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code always_ne_tnpoint_npoint} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 1 temporal</p>
     */
    public static int always_ne_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_ne_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_ne_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code ever_eq_npoint_tnpoint} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 1 temporal</p>
     */
    public static int ever_eq_npoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_eq_npoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_eq_npoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code ever_eq_tnpoint_npoint} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 1 temporal</p>
     */
    public static int ever_eq_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_eq_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_eq_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code ever_ne_npoint_tnpoint} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 1 temporal</p>
     */
    public static int ever_ne_npoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_ne_npoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_ne_npoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code ever_ne_tnpoint_npoint} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 1 temporal</p>
     */
    public static int ever_ne_tnpoint_npoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_ne_tnpoint_npoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_ne_tnpoint_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code route_length} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Free function (not class-classified). Classification rule: sequence-derived metric</p>
     */
    public static double route_length(long arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "route_length requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.route_length(arg0);
    }

    /**
     * MEOS {@code always_eq_tnpoint_tnpoint} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 2 temporals</p>
     */
    public static int always_eq_tnpoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_eq_tnpoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_eq_tnpoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code always_ne_tnpoint_tnpoint} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 2 temporals</p>
     */
    public static int always_ne_tnpoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_ne_tnpoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_ne_tnpoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code ever_eq_tnpoint_tnpoint} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 2 temporals</p>
     */
    public static int ever_eq_tnpoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_eq_tnpoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_eq_tnpoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code ever_ne_tnpoint_tnpoint} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Free function (not class-classified). Classification rule: ever/always over 2 temporals</p>
     */
    public static int ever_ne_tnpoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_ne_tnpoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_ne_tnpoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code nad_tnpoint_tnpoint} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Free function (not class-classified). Classification rule: distance on 2 temporals</p>
     */
    public static double nad_tnpoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nad_tnpoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nad_tnpoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code nai_tnpoint_tnpoint} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Free function (not class-classified). Classification rule: distance on 2 temporals</p>
     */
    public static jnr.ffi.Pointer nai_tnpoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nai_tnpoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nai_tnpoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code shortestline_tnpoint_tnpoint} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Free function (not class-classified). Classification rule: distance on 2 temporals</p>
     */
    public static jnr.ffi.Pointer shortestline_tnpoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "shortestline_tnpoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.shortestline_tnpoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code tdistance_tnpoint_tnpoint} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Free function (not class-classified). Classification rule: distance on 2 temporals</p>
     */
    public static jnr.ffi.Pointer tdistance_tnpoint_tnpoint(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tdistance_tnpoint_tnpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tdistance_tnpoint_tnpoint(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_as_ewkt} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static java.lang.String npoint_as_ewkt(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_as_ewkt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_as_ewkt(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_as_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static java.lang.String npoint_as_hexwkb(jnr.ffi.Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_as_hexwkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_as_hexwkb(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_as_text} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static java.lang.String npoint_as_text(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_as_text requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_as_text(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_as_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static jnr.ffi.Pointer npoint_as_wkb(jnr.ffi.Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_as_wkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_as_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_from_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static jnr.ffi.Pointer npoint_from_hexwkb(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_from_hexwkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_from_hexwkb(arg0);
    }

    /**
     * MEOS {@code npoint_from_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static jnr.ffi.Pointer npoint_from_wkb(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_from_wkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_from_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code npoint_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static jnr.ffi.Pointer npoint_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_in(arg0);
    }

    /**
     * MEOS {@code npoint_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static java.lang.String npoint_out(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "npoint_out requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.npoint_out(arg0, arg1);
    }

    /**
     * MEOS {@code nsegment_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static jnr.ffi.Pointer nsegment_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_in(arg0);
    }

    /**
     * MEOS {@code nsegment_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Free function (not class-classified). Classification rule: IO/serialization</p>
     */
    public static java.lang.String nsegment_out(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "nsegment_out requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.nsegment_out(arg0, arg1);
    }

}
