/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: SpanSet
 * Methods emitted: 30 (bounded-state=20 · io-meta=4 · stateless=3 · windowed=3)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsSpanSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsSpanSet() { /* utility */ }

    /**
     * MEOS {@code spanset_copy} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer spanset_copy(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_copy requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_copy(arg0);
    }

    /**
     * MEOS {@code spanset_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer spanset_make(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_make(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_to_tbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer spanset_to_tbox(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_to_tbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_to_tbox(arg0);
    }

    /**
     * MEOS {@code spanset_cmp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int spanset_cmp(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_cmp requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_end_span} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer spanset_end_span(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_end_span requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_end_span(arg0);
    }

    /**
     * MEOS {@code spanset_eq} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean spanset_eq(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_eq requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_eq(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_ge} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean spanset_ge(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_ge requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_ge(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_gt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean spanset_gt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_gt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_gt(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_hash} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int spanset_hash(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_hash requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_hash(arg0);
    }

    /**
     * MEOS {@code spanset_hash_extended} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int spanset_hash_extended(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_hash_extended requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_hash_extended(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_le} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean spanset_le(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_le requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_le(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_lower_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean spanset_lower_inc(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_lower_inc requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_lower_inc(arg0);
    }

    /**
     * MEOS {@code spanset_lt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean spanset_lt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_lt requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_lt(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_ne} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean spanset_ne(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_ne requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_ne(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_num_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int spanset_num_spans(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_num_spans requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_num_spans(arg0);
    }

    /**
     * MEOS {@code spanset_span} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer spanset_span(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_span requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_span(arg0);
    }

    /**
     * MEOS {@code spanset_span_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer spanset_span_n(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_span_n requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_span_n(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_spanarr} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer spanset_spanarr(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_spanarr requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_spanarr(arg0);
    }

    /**
     * MEOS {@code spanset_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer spanset_spans(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_spans requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_spans(arg0);
    }

    /**
     * MEOS {@code spanset_split_each_n_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer spanset_split_each_n_spans(jnr.ffi.Pointer arg0, int arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_split_each_n_spans requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_split_each_n_spans(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code spanset_split_n_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer spanset_split_n_spans(jnr.ffi.Pointer arg0, int arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_split_n_spans requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_split_n_spans(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code spanset_start_span} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer spanset_start_span(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_start_span requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_start_span(arg0);
    }

    /**
     * MEOS {@code spanset_upper_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean spanset_upper_inc(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_upper_inc requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_upper_inc(arg0);
    }

    /**
     * MEOS {@code spanset_extent_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer spanset_extent_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_extent_transfn requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_extent_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_union_finalfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer spanset_union_finalfn(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_union_finalfn requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_union_finalfn(arg0);
    }

    /**
     * MEOS {@code spanset_union_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer spanset_union_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_union_transfn requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_union_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_as_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String spanset_as_hexwkb(jnr.ffi.Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_as_hexwkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_as_hexwkb(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_as_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer spanset_as_wkb(jnr.ffi.Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_as_wkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_as_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_from_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer spanset_from_hexwkb(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_from_hexwkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_from_hexwkb(arg0);
    }

    /**
     * MEOS {@code spanset_from_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer spanset_from_wkb(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_from_wkb requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.spanset_from_wkb(arg0, arg1);
    }

}
