/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TNumber
 * Methods emitted: 23 (bounded-state=17 · windowed=4 · stateless=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTNumber {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTNumber() { /* utility */ }

    /**
     * MEOS {@code tnumber_to_span} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tnumber_to_span(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_to_span requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_to_span(arg0);
    }

    /**
     * MEOS {@code tnumber_to_tbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tnumber_to_tbox(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_to_tbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_to_tbox(arg0);
    }

    /**
     * MEOS {@code tnumber_abs} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tnumber_abs(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_abs requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_abs(arg0);
    }

    /**
     * MEOS {@code tnumber_angular_difference} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tnumber_angular_difference(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_angular_difference requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_angular_difference(arg0);
    }

    /**
     * MEOS {@code tnumber_at_span} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tnumber_at_span(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_at_span requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_at_span(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_at_spanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tnumber_at_spanset(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_at_spanset requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_at_spanset(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_at_tbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tnumber_at_tbox(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_at_tbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_at_tbox(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_avg_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double tnumber_avg_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_avg_value requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_avg_value(arg0);
    }

    /**
     * MEOS {@code tnumber_delta_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tnumber_delta_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_delta_value requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_delta_value(arg0);
    }

    /**
     * MEOS {@code tnumber_integral} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double tnumber_integral(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_integral requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_integral(arg0);
    }

    /**
     * MEOS {@code tnumber_minus_span} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tnumber_minus_span(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_minus_span requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_minus_span(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_minus_spanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tnumber_minus_spanset(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_minus_spanset requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_minus_spanset(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_minus_tbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer tnumber_minus_tbox(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_minus_tbox requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_minus_tbox(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_split_each_n_tboxes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tnumber_split_each_n_tboxes(jnr.ffi.Pointer arg0, int arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_split_each_n_tboxes requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_split_each_n_tboxes(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tnumber_split_n_tboxes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tnumber_split_n_tboxes(jnr.ffi.Pointer arg0, int arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_split_n_tboxes requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_split_n_tboxes(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tnumber_tboxes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tnumber_tboxes(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_tboxes requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_tboxes(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_trend} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tnumber_trend(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_trend requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_trend(arg0);
    }

    /**
     * MEOS {@code tnumber_twavg} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double tnumber_twavg(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_twavg requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_twavg(arg0);
    }

    /**
     * MEOS {@code tnumber_valuespans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tnumber_valuespans(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_valuespans requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_valuespans(arg0);
    }

    /**
     * MEOS {@code tnumber_extent_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer tnumber_extent_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_extent_transfn requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_extent_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_tavg_finalfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer tnumber_tavg_finalfn(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_tavg_finalfn requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_tavg_finalfn(arg0);
    }

    /**
     * MEOS {@code tnumber_tavg_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer tnumber_tavg_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_tavg_transfn requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_tavg_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code tnumber_wavg_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer tnumber_wavg_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnumber_wavg_transfn requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tnumber_wavg_transfn(arg0, arg1, arg2);
    }

}
