/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TRGeometry
 * Methods emitted: 36 (bounded-state=32 · stateless=3 · io-meta=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTRGeometry {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTRGeometry() { /* utility */ }

    /**
     * MEOS {@code trgeometry_to_tinstant} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer trgeometry_to_tinstant(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_to_tinstant requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_to_tinstant(arg0);
    }

    /**
     * MEOS {@code trgeometry_to_tpoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer trgeometry_to_tpoint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_to_tpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_to_tpoint(arg0);
    }

    /**
     * MEOS {@code trgeometry_to_tpose} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer trgeometry_to_tpose(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_to_tpose requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_to_tpose(arg0);
    }

    /**
     * MEOS {@code trgeometry_after_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_after_timestamptz(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_after_timestamptz requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_after_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_append_tinstant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_append_tinstant(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, int arg2, double arg3, jnr.ffi.Pointer arg4, boolean arg5) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_append_tinstant requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_append_tinstant(arg0, arg1, arg2, arg3, arg4, arg5);
    }

    /**
     * MEOS {@code trgeometry_append_tsequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_append_tsequence(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_append_tsequence requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_append_tsequence(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_before_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_before_timestamptz(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_before_timestamptz requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_before_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_delete_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_delete_timestamptz(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_delete_timestamptz requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_delete_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_delete_tstzset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_delete_tstzset(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_delete_tstzset requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_delete_tstzset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_delete_tstzspan} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_delete_tstzspan(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_delete_tstzspan requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_delete_tstzspan(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_delete_tstzspanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_delete_tstzspanset(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_delete_tstzspanset requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_delete_tstzspanset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_end_instant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_end_instant(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_end_instant requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_end_instant(arg0);
    }

    /**
     * MEOS {@code trgeometry_end_sequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_end_sequence(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_end_sequence requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_end_sequence(arg0);
    }

    /**
     * MEOS {@code trgeometry_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_end_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_end_value requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_end_value(arg0);
    }

    /**
     * MEOS {@code trgeometry_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_geom(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_geom requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_geom(arg0);
    }

    /**
     * MEOS {@code trgeometry_instant_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_instant_n(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_instant_n requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_instant_n(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_instants} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_instants(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_instants requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_instants(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_points} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_points(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_points requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_points(arg0);
    }

    /**
     * MEOS {@code trgeometry_restrict_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_restrict_timestamptz(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_timestamptz requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_tstzset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_restrict_tstzset(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_tstzset requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_tstzset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_tstzspan} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_restrict_tstzspan(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_tstzspan requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_tstzspan(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_tstzspanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_restrict_tstzspanset(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_tstzspanset requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_tstzspanset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_restrict_value(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_value requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_value(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_restrict_values(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_values requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_values(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_rotation} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_rotation(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_rotation requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_rotation(arg0);
    }

    /**
     * MEOS {@code trgeometry_round} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_round(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_round requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_round(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_segments} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_segments(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_segments requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_segments(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_sequence_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_sequence_n(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_sequence_n requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_sequence_n(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_sequences} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_sequences(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_sequences requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_sequences(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_set_interp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_set_interp(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_set_interp requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_set_interp(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_start_instant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_start_instant(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_start_instant requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_start_instant(arg0);
    }

    /**
     * MEOS {@code trgeometry_start_sequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_start_sequence(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_start_sequence requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_start_sequence(arg0);
    }

    /**
     * MEOS {@code trgeometry_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_start_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_start_value requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_start_value(arg0);
    }

    /**
     * MEOS {@code trgeometry_traversed_area} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_traversed_area(jnr.ffi.Pointer arg0, boolean arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_traversed_area requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_traversed_area(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer trgeometry_value_n(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_value_n requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_value_n(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String trgeometry_out(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_out requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_out(arg0);
    }

}
