/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by tools/codegen/emit_h3_facade.py — do not edit by hand.
 * H3 / th3index family facade over functions.GeneratedFunctions.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTh3index {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTh3index() { /* utility */ }

    /** MEOS {@code th3index_are_neighbor_cells} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_are_neighbor_cells(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_are_neighbor_cells requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_are_neighbor_cells(arg0, arg1);
    }

    /** MEOS {@code th3index_cell_area} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_area(jnr.ffi.Pointer arg0, java.lang.String arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_area requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_area(arg0, arg1);
    }

    /** MEOS {@code th3index_cell_to_boundary} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_to_boundary(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_to_boundary requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_to_boundary(arg0);
    }

    /** MEOS {@code th3index_cell_to_center_child} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_to_center_child(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_to_center_child requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_to_center_child(arg0, arg1);
    }

    /** MEOS {@code th3index_cell_to_center_child_next} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_to_center_child_next(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_to_center_child_next requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_to_center_child_next(arg0);
    }

    /** MEOS {@code th3index_cell_to_child_pos} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_to_child_pos(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_to_child_pos requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_to_child_pos(arg0, arg1);
    }

    /** MEOS {@code th3index_cell_to_local_ij} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_to_local_ij(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_to_local_ij requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_to_local_ij(arg0, arg1);
    }

    /** MEOS {@code th3index_cell_to_parent} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_to_parent(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_to_parent requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_to_parent(arg0, arg1);
    }

    /** MEOS {@code th3index_cell_to_parent_next} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_to_parent_next(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_to_parent_next requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_to_parent_next(arg0);
    }

    /** MEOS {@code th3index_cell_to_vertex} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cell_to_vertex(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cell_to_vertex requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cell_to_vertex(arg0, arg1);
    }

    /** MEOS {@code th3index_cells_to_directed_edge} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_cells_to_directed_edge(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_cells_to_directed_edge requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_cells_to_directed_edge(arg0, arg1);
    }

    /** MEOS {@code th3index_child_pos_to_cell} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_child_pos_to_cell(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_child_pos_to_cell requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_child_pos_to_cell(arg0, arg1, arg2);
    }

    /** MEOS {@code th3index_directed_edge_to_boundary} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_directed_edge_to_boundary(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_directed_edge_to_boundary requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_directed_edge_to_boundary(arg0);
    }

    /** MEOS {@code th3index_edge_length} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_edge_length(jnr.ffi.Pointer arg0, java.lang.String arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_edge_length requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_edge_length(arg0, arg1);
    }

    /** MEOS {@code th3index_end_value} — H3 / th3index family. */
    public static long th3index_end_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_end_value requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_end_value(arg0);
    }

    /** MEOS {@code th3index_get_base_cell_number} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_get_base_cell_number(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_get_base_cell_number requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_get_base_cell_number(arg0);
    }

    /** MEOS {@code th3index_get_directed_edge_destination} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_get_directed_edge_destination(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_get_directed_edge_destination requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_get_directed_edge_destination(arg0);
    }

    /** MEOS {@code th3index_get_directed_edge_origin} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_get_directed_edge_origin(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_get_directed_edge_origin requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_get_directed_edge_origin(arg0);
    }

    /** MEOS {@code th3index_get_resolution} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_get_resolution(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_get_resolution requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_get_resolution(arg0);
    }

    /** MEOS {@code th3index_grid_distance} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_grid_distance(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_grid_distance requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_grid_distance(arg0, arg1);
    }

    /** MEOS {@code th3index_in} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_in(arg0);
    }

    /** MEOS {@code th3index_is_pentagon} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_is_pentagon(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_is_pentagon requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_is_pentagon(arg0);
    }

    /** MEOS {@code th3index_is_res_class_iii} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_is_res_class_iii(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_is_res_class_iii requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_is_res_class_iii(arg0);
    }

    /** MEOS {@code th3index_is_valid_cell} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_is_valid_cell(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_is_valid_cell requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_is_valid_cell(arg0);
    }

    /** MEOS {@code th3index_is_valid_directed_edge} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_is_valid_directed_edge(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_is_valid_directed_edge requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_is_valid_directed_edge(arg0);
    }

    /** MEOS {@code th3index_is_valid_vertex} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_is_valid_vertex(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_is_valid_vertex requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_is_valid_vertex(arg0);
    }

    /** MEOS {@code th3index_local_ij_to_cell} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_local_ij_to_cell(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_local_ij_to_cell requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_local_ij_to_cell(arg0, arg1);
    }

    /** MEOS {@code th3index_make} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_make(long arg0, java.time.OffsetDateTime arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_make(arg0, arg1);
    }

    /** MEOS {@code th3index_start_value} — H3 / th3index family. */
    public static long th3index_start_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_start_value requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_start_value(arg0);
    }

    /** MEOS {@code th3index_to_tbigint} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_to_tbigint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_to_tbigint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_to_tbigint(arg0);
    }

    /** MEOS {@code th3index_to_tgeogpoint} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_to_tgeogpoint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_to_tgeogpoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_to_tgeogpoint(arg0);
    }

    /** MEOS {@code th3index_to_tgeompoint} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_to_tgeompoint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_to_tgeompoint requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_to_tgeompoint(arg0);
    }

    /** MEOS {@code th3index_value_at_timestamptz} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_value_at_timestamptz(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_value_at_timestamptz requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_value_at_timestamptz(arg0, arg1, arg2);
    }

    /** MEOS {@code th3index_value_n} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_value_n(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_value_n requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_value_n(arg0, arg1);
    }

    /** MEOS {@code th3index_values} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_values(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_values requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_values(arg0, arg1);
    }

    /** MEOS {@code th3index_vertex_to_latlng} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3index_vertex_to_latlng(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3index_vertex_to_latlng requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3index_vertex_to_latlng(arg0);
    }

    /** MEOS {@code th3indexinst_in} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3indexinst_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3indexinst_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3indexinst_in(arg0);
    }

    /** MEOS {@code th3indexinst_make} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3indexinst_make(long arg0, java.time.OffsetDateTime arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3indexinst_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3indexinst_make(arg0, arg1);
    }

    /** MEOS {@code th3indexseq_in} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3indexseq_in(java.lang.String arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3indexseq_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3indexseq_in(arg0, arg1);
    }

    /** MEOS {@code th3indexseq_make} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3indexseq_make(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, int arg2, boolean arg3, boolean arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3indexseq_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3indexseq_make(arg0, arg1, arg2, arg3, arg4);
    }

    /** MEOS {@code th3indexseqset_in} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3indexseqset_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3indexseqset_in requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3indexseqset_in(arg0);
    }

    /** MEOS {@code th3indexseqset_make} — H3 / th3index family. */
    public static jnr.ffi.Pointer th3indexseqset_make(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "th3indexseqset_make requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.th3indexseqset_make(arg0, arg1);
    }
}
