/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

package org.mobilitydb.meos;

/* AUTO-GENERATED by tools/codegen/emit_h3_facade.py — do not edit by hand.
 * H3 / th3index family facade over functions.GeneratedFunctions.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsFreeH3 {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsFreeH3() { /* utility */ }

    /** MEOS {@code always_eq_h3index_th3index} — H3 / th3index family. */
    public static int always_eq_h3index_th3index(long arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_eq_h3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_eq_h3index_th3index(arg0, arg1);
    }

    /** MEOS {@code always_eq_th3index_h3index} — H3 / th3index family. */
    public static int always_eq_th3index_h3index(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_eq_th3index_h3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_eq_th3index_h3index(arg0, arg1);
    }

    /** MEOS {@code always_eq_th3index_th3index} — H3 / th3index family. */
    public static int always_eq_th3index_th3index(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_eq_th3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_eq_th3index_th3index(arg0, arg1);
    }

    /** MEOS {@code always_ne_h3index_th3index} — H3 / th3index family. */
    public static int always_ne_h3index_th3index(long arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_ne_h3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_ne_h3index_th3index(arg0, arg1);
    }

    /** MEOS {@code always_ne_th3index_h3index} — H3 / th3index family. */
    public static int always_ne_th3index_h3index(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_ne_th3index_h3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_ne_th3index_h3index(arg0, arg1);
    }

    /** MEOS {@code always_ne_th3index_th3index} — H3 / th3index family. */
    public static int always_ne_th3index_th3index(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "always_ne_th3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.always_ne_th3index_th3index(arg0, arg1);
    }

    /** MEOS {@code ever_eq_h3index_th3index} — H3 / th3index family. */
    public static int ever_eq_h3index_th3index(long arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_eq_h3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_eq_h3index_th3index(arg0, arg1);
    }

    /** MEOS {@code ever_eq_h3indexset_th3index} — H3 / th3index family. */
    public static int ever_eq_h3indexset_th3index(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_eq_h3indexset_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_eq_h3indexset_th3index(arg0, arg1);
    }

    /** MEOS {@code ever_eq_th3index_h3index} — H3 / th3index family. */
    public static int ever_eq_th3index_h3index(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_eq_th3index_h3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_eq_th3index_h3index(arg0, arg1);
    }

    /** MEOS {@code ever_eq_th3index_th3index} — H3 / th3index family. */
    public static int ever_eq_th3index_th3index(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_eq_th3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_eq_th3index_th3index(arg0, arg1);
    }

    /** MEOS {@code ever_ne_h3index_th3index} — H3 / th3index family. */
    public static int ever_ne_h3index_th3index(long arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_ne_h3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_ne_h3index_th3index(arg0, arg1);
    }

    /** MEOS {@code ever_ne_th3index_h3index} — H3 / th3index family. */
    public static int ever_ne_th3index_h3index(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_ne_th3index_h3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_ne_th3index_h3index(arg0, arg1);
    }

    /** MEOS {@code ever_ne_th3index_th3index} — H3 / th3index family. */
    public static int ever_ne_th3index_th3index(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ever_ne_th3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.ever_ne_th3index_th3index(arg0, arg1);
    }

    /** MEOS {@code geo_to_h3index_set} — H3 / th3index family. */
    public static jnr.ffi.Pointer geo_to_h3index_set(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "geo_to_h3index_set requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.geo_to_h3index_set(arg0, arg1);
    }

    /** MEOS {@code h3_gs_point_to_cell} — H3 / th3index family. */
    public static long h3_gs_point_to_cell(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "h3_gs_point_to_cell requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.h3_gs_point_to_cell(arg0, arg1);
    }

    /** MEOS {@code tbigint_to_th3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer tbigint_to_th3index(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbigint_to_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tbigint_to_th3index(arg0);
    }

    /** MEOS {@code teq_h3index_th3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer teq_h3index_th3index(long arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "teq_h3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.teq_h3index_th3index(arg0, arg1);
    }

    /** MEOS {@code teq_th3index_h3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer teq_th3index_h3index(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "teq_th3index_h3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.teq_th3index_h3index(arg0, arg1);
    }

    /** MEOS {@code teq_th3index_th3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer teq_th3index_th3index(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "teq_th3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.teq_th3index_th3index(arg0, arg1);
    }

    /** MEOS {@code tgeogpoint_great_circle_distance} — H3 / th3index family. */
    public static jnr.ffi.Pointer tgeogpoint_great_circle_distance(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, java.lang.String arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeogpoint_great_circle_distance requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tgeogpoint_great_circle_distance(arg0, arg1, arg2);
    }

    /** MEOS {@code tgeogpoint_to_th3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer tgeogpoint_to_th3index(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeogpoint_to_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tgeogpoint_to_th3index(arg0, arg1);
    }

    /** MEOS {@code tgeompoint_to_th3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer tgeompoint_to_th3index(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeompoint_to_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tgeompoint_to_th3index(arg0, arg1);
    }

    /** MEOS {@code tne_h3index_th3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer tne_h3index_th3index(long arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tne_h3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tne_h3index_th3index(arg0, arg1);
    }

    /** MEOS {@code tne_th3index_h3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer tne_th3index_h3index(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tne_th3index_h3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tne_th3index_h3index(arg0, arg1);
    }

    /** MEOS {@code tne_th3index_th3index} — H3 / th3index family. */
    public static jnr.ffi.Pointer tne_th3index_th3index(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tne_th3index_th3index requires libmeos — set -Dmeos.enabled=true");
        }
        return GeneratedFunctions.tne_th3index_th3index(arg0, arg1);
    }
}
