#!/usr/bin/env python3
"""Generate the MobilitySpark Spark Connect registrar from the canonical specs.

Inputs (both produced by the sibling extractors, derived from canonical sources):
  - meos-named-surface.json   canonical SQL names + overloads (defaults -> arities)
  - spark-impls.json          each Spark UDF: holder pkg/class/field, arity, types,
                              and the MEOS C functions its body calls

Joining them on the SQL->MEOS C doxygen chain yields canonical name -> Spark impl.
This tool emits MobilitySparkConnectExtensionsGen.scala: a SparkSessionExtensions
that injects each canonical function under its IDENTITY name (no camelCase remap,
no hand-written table). Single-impl functions bind directly to the one impl;
the builder adapts to the call-site arity by null-padding the impl's optional
args (so e.g. asMFJSON(g) reaches the impl's default precision). Multi-impl
functions (one SQL name over several type-specific impls) are listed for the
v2 per-row WKB-type-tag dispatch (meos_typeof_hexwkb) and not emitted here.

Usage: generate_spark_registrar.py [named-surface.json] [spark-impls.json] [out.scala]
"""
import json, os, sys

HERE = os.path.dirname(__file__)
named = json.load(open(sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', 'input', 'meos-named-surface.json')))
impls = json.load(open(sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, '..', 'input', 'spark-impls.json')))['impls']
out = sys.argv[3] if len(sys.argv) > 3 else os.path.join(HERE, '..', 'output', 'MobilitySparkConnectExtensionsGen.scala')

meos2spark = {}
for sn, d in impls.items():
    for mf in d['meosFns']:
        meos2spark.setdefault(mf, []).append(sn)

single, multi = [], []
for fn in named['functions']:
    names = sorted({sn for c in fn['c'] for sn in meos2spark.get(c['meos'], [])})
    if len(names) == 1:
        single.append((fn['name'], names[0]))
    elif len(names) > 1:
        multi.append((fn['name'], names))

lines = []
seen = set()
for canon, spark in single:
    if canon in seen:
        continue
    d = impls[spark]
    seen.add(canon)
    fqn = f"{d['pkg']}.{d['class']}.{d['field']}"
    argts = ', '.join(f'"{t}"' for t in d['argTypes'])
    lines.append(f'    inj(ext, "{canon}", {d["arity"]}, Array[String]({argts}), '
                 f'"{d["retType"]}", {fqn})')

HEADER = '''/* GENERATED by codegen/tools/generate_spark_registrar.py from the canonical
 * named-operation surface (meos-named-surface.json) joined with the MobilitySpark
 * impl scan (spark-impls.json). Do not edit by hand. Each canonical function is
 * injected under its identity name; the camelCase remap and the hand-written
 * registrar are retired. Single-impl functions only; multi-impl functions need
 * the per-row WKB-type-tag dispatch (see the trailing comment). */
package org.mobilitydb.spark.connect

import org.apache.spark.sql.SparkSessionExtensions
import org.apache.spark.sql.catalyst.FunctionIdentifier
import org.apache.spark.sql.catalyst.expressions.{Expression, ExpressionInfo, ScalaUDF}
import org.apache.spark.sql.catalyst.encoders.ExpressionEncoder
import org.apache.spark.sql.types._
import org.apache.spark.sql.api.java.{UDF1, UDF2, UDF3, UDF4}

class MobilitySparkConnectExtensionsGen extends (SparkSessionExtensions => Unit) {
  private lazy val encs: Map[String, ExpressionEncoder[_]] = Map(
    "String" -> ExpressionEncoder[String](), "Integer" -> ExpressionEncoder[java.lang.Integer](),
    "Long" -> ExpressionEncoder[java.lang.Long](), "Double" -> ExpressionEncoder[java.lang.Double](),
    "Number" -> ExpressionEncoder[java.lang.Double](), "Float" -> ExpressionEncoder[java.lang.Float](),
    "Boolean" -> ExpressionEncoder[java.lang.Boolean](), "Timestamp" -> ExpressionEncoder[java.sql.Timestamp]())
  private def enc(t: String) = encs.getOrElse(t, encs("String"))
  private def dt(t: String): DataType = t match {
    case "Integer" => IntegerType; case "Long" => LongType; case "Double" | "Number" => DoubleType
    case "Float" => FloatType; case "Boolean" => BooleanType; case "Timestamp" => TimestampType
    case _ => StringType
  }
  private def inj(ext: SparkSessionExtensions, name: String, arity: Int,
                  argTs: Array[String], retT: String, udf: AnyRef): Unit = {
    val builder = (children: Seq[Expression]) => {
      val n = math.min(children.size, arity)
      ScalaUDF(MobilitySparkConnectExtensionsGen.fn(n, udf, arity), dt(retT), children,
        argTs.take(n).map(t => Some(enc(t))).toSeq, Some(enc(retT)), Some(name))
    }
    try ext.injectFunction((FunctionIdentifier(name), new ExpressionInfo(name, name), builder))
    catch { case _: Throwable => }
  }

  def apply(ext: SparkSessionExtensions): Unit = {
'''

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'w') as f:
    f.write(HEADER)
    f.write('\n'.join(lines))
    f.write('\n  }\n')
    f.write('  // multi-impl (need per-row meos_typeof_hexwkb dispatch, v2):\n')
    for canon, names in multi:
        f.write(f'  //   {canon} -> {names}\n')
    f.write('}\n\n')
    # Companion object: the shipped ScalaUDF closures live here so they capture
    # only the serializable UDF object, never the (non-serializable) extension.
    f.write('''object MobilitySparkConnectExtensionsGen {
  private def call(u: AnyRef, m: Int, a: Seq[Any]): Any = {
    def g(i: Int): AnyRef = if (i < a.length) a(i).asInstanceOf[AnyRef] else null
    m match {
      case 1 => u.asInstanceOf[UDF1[Any, Any]].call(g(0))
      case 2 => u.asInstanceOf[UDF2[Any, Any, Any]].call(g(0), g(1))
      case 3 => u.asInstanceOf[UDF3[Any, Any, Any, Any]].call(g(0), g(1), g(2))
      case _ => u.asInstanceOf[UDF4[Any, Any, Any, Any, Any]].call(g(0), g(1), g(2), g(3))
    }
  }
  def fn(n: Int, u: AnyRef, m: Int): AnyRef = n match {
    case 1 => (a: Any) => call(u, m, Seq(a))
    case 2 => (a: Any, b: Any) => call(u, m, Seq(a, b))
    case 3 => (a: Any, b: Any, c: Any) => call(u, m, Seq(a, b, c))
    case _ => (a: Any, b: Any, c: Any, d: Any) => call(u, m, Seq(a, b, c, d))
  }
}
''')
print(f"single-impl injected: {len(lines)}   multi-impl (v2 dispatch): {len(multi)}   -> {out}")
