#!/usr/bin/env python3
"""Emit the tbigint temporal-type family facade (MeosOpsTBigint).

The consolidated functions.GeneratedFunctions jar carries the tbigint temporal
type (MobilityDB #1044). The static bigint set/span types already have facade
classes (MeosOpsBigintSet/Span/SpanSet); this emits the temporal type's surface
— the numerator is the public meos.h externs whose name contains 'tbigint'
intersected with the jar (Datum-bearing dispatchers are excluded, not being
extern-declared in the public header). Mirrors the per-family facade classes
(MeosOpsTInt/TFloat/…) and the th3index family-port.

Run from :
    MEOS_INCLUDE=<dir-with-meos.h> python3 tools/codegen/emit_tbigint_facade.py jar/JMEOS.jar
"""

# Canonical MobilityDB PostgreSQL-License header, emitted on every generated file.
MEOS_LICENSE_BANNER = (
    '/*****************************************************************************\n'
    ' *\n'
    ' * This MobilityDB code is provided under The PostgreSQL License.\n'
    ' * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB\n'
    ' * contributors\n'
    ' *\n'
    ' * Permission to use, copy, modify, and distribute this software and its\n'
    ' * documentation for any purpose, without fee, and without a written\n'
    ' * agreement is hereby granted, provided that the above copyright notice and\n'
    ' * this paragraph and the following two paragraphs appear in all copies.\n'
    ' *\n'
    ' * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR\n'
    ' * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING\n'
    ' * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,\n'
    ' * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY\n'
    ' * OF SUCH DAMAGE.\n'
    ' *\n'
    ' * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,\n'
    ' * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY\n'
    ' * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON\n'
    ' * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO\n'
    ' * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n'
    ' *\n'
    ' *****************************************************************************/'
)
import re, os, sys, subprocess

HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FACADE = os.path.join(HERE, "src/main/java/org/mobilitydb/meos")
INC = os.environ.get("MEOS_INCLUDE", "/home/esteban/src/MobilityDB/meos/include")
_SIG = re.compile(r'public static (\S+) ([a-z_][A-Za-z0-9_]*)\(([^)]*)\)')
_DECL = re.compile(r'^\s*extern\s+.+?\b([a-z][A-Za-z0-9_]*)\s*\(', re.M)


def jar_sigs(jar):
    out = subprocess.run(["javap", "-classpath", jar, "-p", "functions.GeneratedFunctions"],
                         capture_output=True, text=True).stdout
    sigs = {}
    for line in out.splitlines():
        m = _SIG.search(line)
        if m:
            sigs[m.group(2)] = (m.group(1),
                                [a.strip() for a in m.group(3).strip().split(",")] if m.group(3).strip() else [])
    return sigs


def main():
    jar = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "jar/JMEOS.jar")
    sigs = jar_sigs(jar)
    public = set(_DECL.findall(open(os.path.join(INC, "meos.h")).read()))
    names = sorted(n for n in public if "tbigint" in n and n in sigs)
    body = ""
    for name in names:
        ret, types = sigs[name]
        decl = ", ".join(f"{t} arg{i}" for i, t in enumerate(types))
        call = ", ".join(f"arg{i}" for i in range(len(types)))
        retkw = "" if ret == "void" else "return "
        body += (f"\n    /** MEOS {{@code {name}}} — tbigint temporal family. */\n"
                 f"    public static {ret} {name}({decl}) {{\n"
                 f"        if (!MEOS_AVAILABLE) {{\n"
                 f"            throw new UnsupportedOperationException(\n"
                 f'                "{name} requires libmeos — set -Dmeos.enabled=true");\n'
                 f"        }}\n"
                 f"        {retkw}GeneratedFunctions.{name}({call});\n"
                 f"    }}\n")
    txt = (MEOS_LICENSE_BANNER + "\n\n" + "package org.mobilitydb.meos;\n\n"
           "/* AUTO-GENERATED by tools/codegen/emit_tbigint_facade.py — do not edit by hand.\n"
           " * tbigint temporal-type family facade over functions.GeneratedFunctions.\n */\n\n"
           "import functions.GeneratedFunctions;\n"
           "import jnr.ffi.Pointer;\n\n"
           "public final class MeosOpsTBigint {\n\n"
           "    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;\n\n"
           "    private MeosOpsTBigint() { /* utility */ }\n"
           f"{body}}}\n")
    open(os.path.join(FACADE, "MeosOpsTBigint.java"), "w").write(txt)
    print(f"MeosOpsTBigint: {len(names)} methods")


if __name__ == "__main__":
    main()
