#!/usr/bin/env python3
"""Emit the H3 / th3index family facade (MeosOpsTh3index + MeosOpsFreeH3).

The unified functions.GeneratedFunctions jar carries the H3 temporal-index
family. This emits its user-facing surface as MeosOps* forwarders, mirroring the
other per-family facade classes: the numerator is the public meos_h3.h externs
intersected with the jar (Datum-bearing dispatchers and internal h3 helpers are
excluded by construction — they are not declared in meos_h3.h). th3index_* go to
the temporal-type class MeosOpsTh3index; the remaining H3 free functions (geo↔H3
walkers, set ops, ever/always comparisons) go to MeosOpsFreeH3.

Run from :
    MEOS_INCLUDE=<dir-with-meos_h3.h> python3 tools/codegen/emit_h3_facade.py jar/JMEOS.jar
"""

# Canonical MobilityDB PostgreSQL-License header, emitted on every generated file.
MEOS_LICENSE_BANNER = (
    '/*****************************************************************************\n'
    ' *\n'
    ' * This MobilityDB code is provided under The PostgreSQL License.\n'
    ' * Copyright (c) 2020-2026, Université libre de Bruxelles and MobilityDB\n'
    ' * contributors\n'
    ' *\n'
    ' * Permission to use, copy, modify, and distribute this software and its\n'
    ' * documentation for any purpose, without fee, and without a written\n'
    ' * agreement is hereby granted, provided that the above copyright notice and\n'
    ' * this paragraph and the following two paragraphs appear in all copies.\n'
    ' *\n'
    ' * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR\n'
    ' * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING\n'
    ' * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,\n'
    ' * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY\n'
    ' * OF SUCH DAMAGE.\n'
    ' *\n'
    ' * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,\n'
    ' * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY\n'
    ' * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON\n'
    ' * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO\n'
    ' * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n'
    ' *\n'
    ' *****************************************************************************/'
)
import re, os, sys, subprocess

HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FACADE = os.path.join(HERE, "src/main/java/org/mobilitydb/meos")
INC = os.environ.get("MEOS_INCLUDE", "/home/esteban/src/MobilityDB/meos/include")
_SIG = re.compile(r'public static (\S+) ([a-z_][A-Za-z0-9_]*)\(([^)]*)\)')
_DECL = re.compile(r'^\s*extern\s+.+?\b([a-z][A-Za-z0-9_]*)\s*\(', re.M)


def jar_sigs(jar):
    out = subprocess.run(["javap", "-classpath", jar, "-p", "functions.GeneratedFunctions"],
                         capture_output=True, text=True).stdout
    sigs = {}
    for line in out.splitlines():
        m = _SIG.search(line)
        if m:
            sigs[m.group(2)] = (m.group(1),
                                [a.strip() for a in m.group(3).strip().split(",")] if m.group(3).strip() else [])
    return sigs


def method(name, sigs):
    ret, types = sigs[name]
    decl = ", ".join(f"{t} arg{i}" for i, t in enumerate(types))
    call = ", ".join(f"arg{i}" for i in range(len(types)))
    retkw = "" if ret == "void" else "return "
    return (f"\n    /** MEOS {{@code {name}}} — H3 / th3index family. */\n"
            f"    public static {ret} {name}({decl}) {{\n"
            f"        if (!MEOS_AVAILABLE) {{\n"
            f"            throw new UnsupportedOperationException(\n"
            f'                "{name} requires libmeos — set -Dmeos.enabled=true");\n'
            f"        }}\n"
            f"        {retkw}GeneratedFunctions.{name}({call});\n"
            f"    }}\n")


def emit_class(cls, names, sigs):
    body = "".join(method(n, sigs) for n in names)
    txt = (MEOS_LICENSE_BANNER + "\n\n" + f"package org.mobilitydb.meos;\n\n"
           f"/* AUTO-GENERATED by tools/codegen/emit_h3_facade.py — do not edit by hand.\n"
           f" * H3 / th3index family facade over functions.GeneratedFunctions.\n */\n\n"
           f"import functions.GeneratedFunctions;\n"
           f"import jnr.ffi.Pointer;\n\n"
           f"public final class {cls} {{\n\n"
           f"    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;\n\n"
           f"    private {cls}() {{ /* utility */ }}\n"
           f"{body}}}\n")
    open(os.path.join(FACADE, f"{cls}.java"), "w").write(txt)
    return len(names)


def main():
    jar = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "jar/JMEOS.jar")
    sigs = jar_sigs(jar)
    public = set(_DECL.findall(open(os.path.join(INC, "meos_h3.h")).read()))
    facade = sorted(public & set(sigs))
    th3 = [n for n in facade if n.startswith("th3index")]
    free = [n for n in facade if not n.startswith("th3index")]
    a = emit_class("MeosOpsTh3index", th3, sigs)
    b = emit_class("MeosOpsFreeH3", free, sigs)
    print(f"MeosOpsTh3index: {a} methods; MeosOpsFreeH3: {b} methods")


if __name__ == "__main__":
    main()
