/* GENERATED by codegen/tools/generate_spark_registrar.py from the canonical
 * named-operation surface (meos-named-surface.json) joined with the MobilitySpark
 * impl scan (spark-impls.json). Do not edit by hand. Each canonical function is
 * injected under its identity name (no camelCase remap, no hand-written table).
 * Single-impl functions bind to the one impl; multi-impl functions that differ on
 * arg0's MEOS type dispatch per row on the arg0 WKB type tag. Functions that
 * differ only on a later argument are listed in the trailing comment. */
package org.mobilitydb.spark.connect

import org.apache.spark.sql.SparkSessionExtensions
import org.apache.spark.sql.catalyst.FunctionIdentifier
import org.apache.spark.sql.catalyst.expressions.{Expression, ExpressionInfo, ScalaUDF}
import org.apache.spark.sql.catalyst.encoders.ExpressionEncoder
import org.apache.spark.sql.types._
import org.apache.spark.sql.api.java.{UDF1, UDF2, UDF3, UDF4}
import functions.GeneratedFunctions

class MobilitySparkConnectExtensionsGen extends (SparkSessionExtensions => Unit) {
  private lazy val encs: Map[String, ExpressionEncoder[_]] = Map(
    "String" -> ExpressionEncoder[String](), "Integer" -> ExpressionEncoder[java.lang.Integer](),
    "Long" -> ExpressionEncoder[java.lang.Long](), "Double" -> ExpressionEncoder[java.lang.Double](),
    "Number" -> ExpressionEncoder[java.lang.Double](), "Float" -> ExpressionEncoder[java.lang.Float](),
    "Boolean" -> ExpressionEncoder[java.lang.Boolean](), "Timestamp" -> ExpressionEncoder[java.sql.Timestamp]())
  private def enc(t: String) = encs.getOrElse(t, encs("String"))
  private def dt(t: String): DataType = t match {
    case "Integer" => IntegerType; case "Long" => LongType; case "Double" | "Number" => DoubleType
    case "Float" => FloatType; case "Boolean" => BooleanType; case "Timestamp" => TimestampType
    case _ => StringType
  }
  private def inj(ext: SparkSessionExtensions, name: String, arity: Int,
                  argTs: Array[String], retT: String, udf: AnyRef, defaults: Array[AnyRef]): Unit = {
    val builder = (children: Seq[Expression]) => {
      val n = math.min(children.size, arity)
      ScalaUDF(MobilitySparkConnectExtensionsGen.fn(n, udf, arity, defaults), dt(retT), children,
        argTs.take(n).map(t => Some(enc(t))).toSeq, Some(enc(retT)), Some(name))
    }
    try ext.injectFunction((FunctionIdentifier(name), new ExpressionInfo(name, name), builder))
    catch { case _: Throwable => }
  }
  // One SQL name over several type-specific impls: dispatch per row on the
  // differentiating argument's MEOS type tag to the impl whose receiver matches.
  // Each route carries (impl, impl arity, impl SQL-default fills).
  private def injMulti(ext: SparkSessionExtensions, name: String, dpos: Int, retT: String,
                       routes: Map[String, (AnyRef, Int, Array[AnyRef])],
                       dflt: (AnyRef, Int, Array[AnyRef])): Unit = {
    val builder = (children: Seq[Expression]) => {
      val n = children.size
      ScalaUDF(MobilitySparkConnectExtensionsGen.disp(n, dpos, routes, dflt), dt(retT), children,
        children.map(_ => Some(enc("String"))), Some(enc(retT)), Some(name))
    }
    try ext.injectFunction((FunctionIdentifier(name), new ExpressionInfo(name, name), builder))
    catch { case _: Throwable => }
  }

  def apply(ext: SparkSessionExtensions): Unit = {
    inj(ext, "Ymax", 1, Array[String]("String"), "Double", org.mobilitydb.spark.geo.STBoxUDFs.stboxYmax, Array[AnyRef](null))
    inj(ext, "Ymin", 1, Array[String]("String"), "Double", org.mobilitydb.spark.geo.STBoxUDFs.stboxYmin, Array[AnyRef](null))
    inj(ext, "Zmax", 1, Array[String]("String"), "Double", org.mobilitydb.spark.geo.STBoxUDFs.stboxZmax, Array[AnyRef](null))
    inj(ext, "Zmin", 1, Array[String]("String"), "Double", org.mobilitydb.spark.geo.STBoxUDFs.stboxZmin, Array[AnyRef](null))
    inj(ext, "aDisjoint", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.demo.BerlinMODUDFs.aDisjoint, Array[AnyRef](null, null))
    inj(ext, "abs", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MathGapUDFs.abs, Array[AnyRef](null))
    inj(ext, "appendInstant", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.appendInstant, Array[AnyRef](null, null))
    inj(ext, "appendSequence", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.appendSequence, Array[AnyRef](null, null))
    inj(ext, "asEWKT", 2, Array[String]("String", "Integer"), "String", org.mobilitydb.spark.geo.GeoAnalyticsUDFs.asEWKT, Array[AnyRef](null, (Integer.valueOf(15): AnyRef)))
    inj(ext, "asMFJSON", 2, Array[String]("String", "Integer"), "String", org.mobilitydb.spark.temporal.TemporalUDFs.temporalAsMfjson, Array[AnyRef](null, null))
    inj(ext, "asText", 2, Array[String]("String", "Integer"), "String", org.mobilitydb.spark.geo.GeoAnalyticsUDFs.asText, Array[AnyRef](null, (Integer.valueOf(15): AnyRef)))
    inj(ext, "atMax", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.atMax, Array[AnyRef](null))
    inj(ext, "atMin", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.atMin, Array[AnyRef](null))
    inj(ext, "atStbox", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.atStbox, Array[AnyRef](null, null))
    inj(ext, "atTbox", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.SetSpanGapUDFs.atTbox, Array[AnyRef](null, null))
    inj(ext, "atValues", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.atValues, Array[AnyRef](null, null))
    inj(ext, "azimuth", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AnalyticsUDFs.tpointAzimuth, Array[AnyRef](null))
    inj(ext, "bigintspan", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.SetSpanGapUDFs.bigintSpan, Array[AnyRef](null))
    inj(ext, "convexHull", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.tpointConvexHull, Array[AnyRef](null))
    inj(ext, "cumulativeLength", 1, Array[String]("String"), "String", org.mobilitydb.spark.geo.GeoUDFs.cumulativeLength, Array[AnyRef](null))
    inj(ext, "dateN", 2, Array[String]("String", "Integer"), "Integer", org.mobilitydb.spark.temporal.AccessorAliasUDFs.dateN, Array[AnyRef](null, null))
    inj(ext, "dates", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorAliasUDFs.dates, Array[AnyRef](null))
    inj(ext, "dateset", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.TransformUDFs.tstzsetToDateset, Array[AnyRef](null))
    inj(ext, "deltaValue", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MathGapUDFs.deltavalue, Array[AnyRef](null))
    inj(ext, "derivative", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MathGapUDFs.derivative, Array[AnyRef](null))
    inj(ext, "direction", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AnalyticsUDFs.tpointDirection, Array[AnyRef](null))
    inj(ext, "douglasPeuckerSimplify", 2, Array[String]("String", "Double"), "String", org.mobilitydb.spark.temporal.TransformUDFs.temporalSimplifyDp, Array[AnyRef](null, null))
    inj(ext, "dynTimeWarpDistance", 2, Array[String]("String", "String"), "Double", org.mobilitydb.spark.temporal.SimilarityUDFs.dynamicTimeWarp, Array[AnyRef](null, null))
    inj(ext, "eContains", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.geo.GeoUDFs.eContains, Array[AnyRef](null, null))
    inj(ext, "eCovers", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.geo.GeoUDFs.eCovers, Array[AnyRef](null, null))
    inj(ext, "eIntersects", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.geo.GeoUDFs.eIntersectsTgeoTgeo, Array[AnyRef](null, null))
    inj(ext, "eTouches", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.geo.GeoUDFs.eTouches, Array[AnyRef](null, null))
    inj(ext, "endDate", 1, Array[String]("String"), "Integer", org.mobilitydb.spark.temporal.AccessorAliasUDFs.endDate, Array[AnyRef](null))
    inj(ext, "endInstant", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.endInstant, Array[AnyRef](null))
    inj(ext, "endSequence", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.endSequence, Array[AnyRef](null))
    inj(ext, "endSpan", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.SetSpanGapUDFs.endSpan, Array[AnyRef](null))
    inj(ext, "expandSpace", 2, Array[String]("String", "Number"), "String", org.mobilitydb.spark.geo.GeoUDFs.expandSpace, Array[AnyRef](null, null))
    inj(ext, "expandTime", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.TBoxUDFs.tboxExpandTime, Array[AnyRef](null, null))
    inj(ext, "floatset", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.intsetToFloatset, Array[AnyRef](null))
    inj(ext, "floatspanset", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.TransformUDFs.intspansetToFloat, Array[AnyRef](null))
    inj(ext, "frechetDistance", 2, Array[String]("String", "String"), "Double", org.mobilitydb.spark.temporal.SimilarityUDFs.frechetDistance, Array[AnyRef](null, null))
    inj(ext, "geometry", 1, Array[String]("String"), "String", org.mobilitydb.spark.geo.STBoxUDFs.stboxToGeo, Array[AnyRef](null))
    inj(ext, "getSpace", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorGapUDFs.getSpace, Array[AnyRef](null))
    inj(ext, "getTime", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.SubtypeConstructorUDFs.getTime, Array[AnyRef](null))
    inj(ext, "getX", 1, Array[String]("String"), "String", org.mobilitydb.spark.geo.GeoUDFs.getX, Array[AnyRef](null))
    inj(ext, "getY", 1, Array[String]("String"), "String", org.mobilitydb.spark.geo.GeoUDFs.getY, Array[AnyRef](null))
    inj(ext, "getZ", 1, Array[String]("String"), "String", org.mobilitydb.spark.geo.GeoUDFs.getZ, Array[AnyRef](null))
    inj(ext, "hasZ", 1, Array[String]("String"), "Boolean", org.mobilitydb.spark.geo.STBoxUDFs.stboxHasz, Array[AnyRef](null))
    inj(ext, "initcap", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.TransformUDFs.textsetInitcap, Array[AnyRef](null))
    inj(ext, "insert", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.insert, Array[AnyRef](null, null))
    inj(ext, "instantN", 2, Array[String]("String", "Integer"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.instantN, Array[AnyRef](null, null))
    inj(ext, "interp", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.interp, Array[AnyRef](null))
    inj(ext, "intset", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.floatsetToIntset, Array[AnyRef](null))
    inj(ext, "intsetFromHexWKB", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.IOAliasUDFs.asHexEWKB, Array[AnyRef](null))
    inj(ext, "isGeodetic", 1, Array[String]("String"), "Boolean", org.mobilitydb.spark.geo.STBoxUDFs.stboxIsGeodetic, Array[AnyRef](null))
    inj(ext, "length", 1, Array[String]("String"), "Double", org.mobilitydb.spark.demo.BerlinMODUDFs.length, Array[AnyRef](null))
    inj(ext, "lowerInc", 1, Array[String]("String"), "Boolean", org.mobilitydb.spark.temporal.MoreAccessorUDFs.lowerInc, Array[AnyRef](null))
    inj(ext, "maxInstant", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.maxInstant, Array[AnyRef](null))
    inj(ext, "merge", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.merge, Array[AnyRef](null, null))
    inj(ext, "minDistSimplify", 2, Array[String]("String", "Double"), "String", org.mobilitydb.spark.temporal.TransformUDFs.temporalSimplifyMinDist, Array[AnyRef](null, null))
    inj(ext, "minDistance", 2, Array[String]("Object", "Object"), "Double", org.mobilitydb.spark.geo.DistanceUDFs.minDistanceTgeoarrTgeoarr, Array[AnyRef](null, null))
    inj(ext, "minInstant", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.minInstant, Array[AnyRef](null))
    inj(ext, "minTimeDeltaSimplify", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.TransformUDFs.temporalSimplifyMinTdelta, Array[AnyRef](null, null))
    inj(ext, "minusMax", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.minusMax, Array[AnyRef](null))
    inj(ext, "minusMin", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.minusMin, Array[AnyRef](null))
    inj(ext, "minusStbox", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.minusStbox, Array[AnyRef](null, null))
    inj(ext, "minusTbox", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.SetSpanGapUDFs.minusTbox, Array[AnyRef](null, null))
    inj(ext, "minusValues", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorGapUDFs.minusValues, Array[AnyRef](null, null))
    inj(ext, "nearestApproachDistance", 2, Array[String]("String", "String"), "Double", org.mobilitydb.spark.geo.GeoUDFs.nearestApproachDistance, Array[AnyRef](null, null))
    inj(ext, "numDates", 1, Array[String]("String"), "Integer", org.mobilitydb.spark.temporal.AccessorAliasUDFs.numDates, Array[AnyRef](null))
    inj(ext, "numInstants", 1, Array[String]("String"), "Integer", org.mobilitydb.spark.temporal.TemporalUDFs.numInstants, Array[AnyRef](null))
    inj(ext, "numSequences", 1, Array[String]("String"), "Integer", org.mobilitydb.spark.temporal.AccessorUDFs.numSequences, Array[AnyRef](null))
    inj(ext, "numSpans", 1, Array[String]("String"), "Integer", org.mobilitydb.spark.temporal.SetSpanGapUDFs.numSpans, Array[AnyRef](null))
    inj(ext, "numTimestamps", 1, Array[String]("String"), "Integer", org.mobilitydb.spark.temporal.MoreAccessorUDFs.numTimestamps, Array[AnyRef](null))
    inj(ext, "numValues", 1, Array[String]("String"), "Integer", org.mobilitydb.spark.temporal.SpanAccessorUDFs.setNumValues, Array[AnyRef](null))
    inj(ext, "scaleTime", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.scale, Array[AnyRef](null, null))
    inj(ext, "sequenceN", 2, Array[String]("String", "Integer"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.sequenceN, Array[AnyRef](null, null))
    inj(ext, "setInterp", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.TransformUDFs.temporalSetInterp, Array[AnyRef](null, null))
    inj(ext, "set_contains", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.setContains, Array[AnyRef](null, null))
    inj(ext, "set_intersection", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.setIntersection, Array[AnyRef](null, null))
    inj(ext, "set_minus", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.setMinus, Array[AnyRef](null, null))
    inj(ext, "set_overlaps", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.setOverlaps, Array[AnyRef](null, null))
    inj(ext, "set_union", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.setUnion, Array[AnyRef](null, null))
    inj(ext, "shortestLine", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.geo.DistanceUDFs.shortestLineTgeoTgeo, Array[AnyRef](null, null))
    inj(ext, "spanN", 2, Array[String]("String", "Integer"), "String", org.mobilitydb.spark.temporal.SetSpanGapUDFs.spann, Array[AnyRef](null, null))
    inj(ext, "span_adjacent", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.spanAdjacent, Array[AnyRef](null, null))
    inj(ext, "span_left", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.spanLeft, Array[AnyRef](null, null))
    inj(ext, "span_overleft", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.spanOverleft, Array[AnyRef](null, null))
    inj(ext, "span_overright", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.spanOverright, Array[AnyRef](null, null))
    inj(ext, "span_right", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.SpanAlgebraUDFs.spanRight, Array[AnyRef](null, null))
    inj(ext, "speed", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.TemporalUDFs.speed, Array[AnyRef](null))
    inj(ext, "startDate", 1, Array[String]("String"), "Integer", org.mobilitydb.spark.temporal.AccessorAliasUDFs.startDate, Array[AnyRef](null))
    inj(ext, "startInstant", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.startInstant, Array[AnyRef](null))
    inj(ext, "startSequence", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MoreAccessorUDFs.startSequence, Array[AnyRef](null))
    inj(ext, "startSpan", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.SetSpanGapUDFs.startSpan, Array[AnyRef](null))
    inj(ext, "stboxFromHexWKB", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorAliasUDFs.box2d, Array[AnyRef](null))
    inj(ext, "stbox_intersection", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.SetSpanGapUDFs.stboxIntersection, Array[AnyRef](null, null))
    inj(ext, "stbox_overlaps", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.demo.BerlinMODUDFs.stboxOverlaps, Array[AnyRef](null, null))
    inj(ext, "stbox_union", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.SetSpanGapUDFs.stboxUnion, Array[AnyRef](null, null))
    inj(ext, "tCovers", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.geo.TempSpatialRelsUDFs.tCoversTgeoGeo, Array[AnyRef](null, null))
    inj(ext, "tempSubtype", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.SubtypeConstructorUDFs.tempSubtype, Array[AnyRef](null))
    inj(ext, "temporal_after", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.PosOpsUDFs.temporalAfterSpan, Array[AnyRef](null, null))
    inj(ext, "temporal_before", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.PosOpsUDFs.temporalBeforeSpan, Array[AnyRef](null, null))
    inj(ext, "temporal_overafter", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.PosOpsUDFs.temporalOverafterSpan, Array[AnyRef](null, null))
    inj(ext, "temporal_overbefore", 2, Array[String]("String", "String"), "Boolean", org.mobilitydb.spark.temporal.PosOpsUDFs.temporalOverbeforeSpan, Array[AnyRef](null, null))
    inj(ext, "temporal_teq", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.BoolOpsUDFs.teqTemporalTemporal, Array[AnyRef](null, null))
    inj(ext, "temporal_tge", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.BoolOpsUDFs.tgeTemporalTemporal, Array[AnyRef](null, null))
    inj(ext, "temporal_tgt", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.BoolOpsUDFs.tgtTemporalTemporal, Array[AnyRef](null, null))
    inj(ext, "temporal_tle", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.BoolOpsUDFs.tleTemporalTemporal, Array[AnyRef](null, null))
    inj(ext, "temporal_tlt", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.BoolOpsUDFs.tltTemporalTemporal, Array[AnyRef](null, null))
    inj(ext, "temporal_tne", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.BoolOpsUDFs.tneTemporalTemporal, Array[AnyRef](null, null))
    inj(ext, "tfloat", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.TransformUDFs.tintToTfloat, Array[AnyRef](null))
    inj(ext, "timestampN", 2, Array[String]("String", "Integer"), "Timestamp", org.mobilitydb.spark.temporal.MoreAccessorUDFs.timestampN, Array[AnyRef](null, null))
    inj(ext, "tintFromHexWKB", 1, Array[String]("String"), "String", org.mobilitydb.spark.npoint.NpointUDFs.routes, Array[AnyRef](null))
    inj(ext, "tintInst", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.TransformUDFs.temporalToTInstant, Array[AnyRef](null))
    inj(ext, "tintSeq", 1, Array[String]("String"), "String", org.mobilitydb.spark.pose.PoseUDFs.tposeSeq, Array[AnyRef](null))
    inj(ext, "tintSeqSet", 2, Array[String]("String", "Timestamp"), "String", org.mobilitydb.spark.temporal.SubtypeConstructorUDFs.ttextInst, Array[AnyRef](null, null))
    inj(ext, "tintSeqSetGaps", 2, Array[String]("String[]", "String"), "String", org.mobilitydb.spark.pose.PoseUDFs.tposeSeqSetGaps, Array[AnyRef](null, null))
    inj(ext, "trajectory", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.TransformUDFs.tpointTrajectory, Array[AnyRef](null))
    inj(ext, "traversedArea", 2, Array[String]("String", "Boolean"), "String", org.mobilitydb.spark.temporal.AccessorGapUDFs.traversedArea, Array[AnyRef](null, (java.lang.Boolean.FALSE: AnyRef)))
    inj(ext, "trend", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.MathGapUDFs.trend, Array[AnyRef](null))
    inj(ext, "twAvg", 1, Array[String]("String"), "Double", org.mobilitydb.spark.temporal.MathGapUDFs.twavg, Array[AnyRef](null))
    inj(ext, "twCentroid", 1, Array[String]("String"), "String", org.mobilitydb.spark.geo.GeoAnalyticsUDFs.twCentroid, Array[AnyRef](null))
    inj(ext, "update", 2, Array[String]("String", "String"), "String", org.mobilitydb.spark.temporal.AccessorUDFs.update, Array[AnyRef](null, null))
    inj(ext, "upperInc", 1, Array[String]("String"), "Boolean", org.mobilitydb.spark.temporal.MoreAccessorUDFs.upperInc, Array[AnyRef](null))
    inj(ext, "valueSpan", 1, Array[String]("String"), "String", org.mobilitydb.spark.temporal.AccessorAliasUDFs.valueSpan, Array[AnyRef](null))
    inj(ext, "volume", 1, Array[String]("String"), "Double", org.mobilitydb.spark.geo.STBoxUDFs.stboxVolume, Array[AnyRef](null))
    inj(ext, "whenTrue", 1, Array[String]("String"), "String", org.mobilitydb.spark.demo.BerlinMODUDFs.whenTrue, Array[AnyRef](null))

    // multi-impl: per-row arg0 MEOS-type-tag dispatch
    injMulti(ext, "SRID", 0, "Integer", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxSrid: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.MoreAccessorUDFs.tpointSrid: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "Tmax", 0, "java.sql.Timestamp", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxTmax: AnyRef, 1, Array[AnyRef](null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxTmax: AnyRef, 1, Array[AnyRef](null))), null)
    injMulti(ext, "Tmin", 0, "java.sql.Timestamp", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxTmin: AnyRef, 1, Array[AnyRef](null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxTmin: AnyRef, 1, Array[AnyRef](null))), null)
    injMulti(ext, "Xmax", 0, "Double", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxXmax: AnyRef, 1, Array[AnyRef](null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxXmax: AnyRef, 1, Array[AnyRef](null))), null)
    injMulti(ext, "Xmin", 0, "Double", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxXmin: AnyRef, 1, Array[AnyRef](null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxXmin: AnyRef, 1, Array[AnyRef](null))), null)
    injMulti(ext, "asHexWKB", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.temporal.TileUDFs.getSpaceTile: AnyRef, 5, Array[AnyRef](null, null, null, null, null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxExpandFloat: AnyRef, 2, Array[AnyRef](null, null))), (org.mobilitydb.spark.temporal.SubtypeConstructorUDFs.afterTimestamp: AnyRef, 2, Array[AnyRef](null, null)))
    injMulti(ext, "atTime", 1, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("tstzset" -> (org.mobilitydb.spark.temporal.RestrictionUDFs.temporalAtTstzset: AnyRef, 2, Array[AnyRef](null, null)), "tstzspan" -> (org.mobilitydb.spark.temporal.AccessorUDFs.atSpan: AnyRef, 2, Array[AnyRef](null, null)), "tstzspanset" -> (org.mobilitydb.spark.temporal.AccessorUDFs.atSpanset: AnyRef, 2, Array[AnyRef](null, null))), null)
    injMulti(ext, "ceil", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("floatset" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatsetCeil: AnyRef, 1, Array[AnyRef](null)), "floatspanset" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatspansetCeil: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.MathGapUDFs.ceil: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "degrees", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("floatset" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatsetDegrees: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.MathGapUDFs.degrees: AnyRef, 2, Array[AnyRef](null, (java.lang.Boolean.FALSE: AnyRef))))
    injMulti(ext, "deleteTime", 1, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("tstzset" -> (org.mobilitydb.spark.temporal.RestrictionUDFs.temporalDeleteTstzset: AnyRef, 2, Array[AnyRef](null, null)), "tstzspan" -> (org.mobilitydb.spark.temporal.RestrictionUDFs.temporalDeleteTstzspan: AnyRef, 2, Array[AnyRef](null, null)), "tstzspanset" -> (org.mobilitydb.spark.temporal.RestrictionUDFs.temporalDeleteTstzspanset: AnyRef, 2, Array[AnyRef](null, null))), null)
    injMulti(ext, "duration", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("datespan" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.datespanDuration: AnyRef, 1, Array[AnyRef](null)), "tstzspan" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.tstzspanDuration: AnyRef, 1, Array[AnyRef](null)), "tstzspanset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzspansetDuration: AnyRef, 2, Array[AnyRef](null, (java.lang.Boolean.FALSE: AnyRef)))), (org.mobilitydb.spark.temporal.MoreAccessorUDFs.duration: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "endTimestamp", 0, "Timestamp", Map[String, (AnyRef, Int, Array[AnyRef])]("tstzspanset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzspansetEndTimestamptz: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.TemporalUDFs.endTimestamp: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "floor", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("floatset" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatsetFloor: AnyRef, 1, Array[AnyRef](null)), "floatspanset" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatspansetFloor: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.MathGapUDFs.floor: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "getValues", 0, "java.sql.Date", Map[String, (AnyRef, Int, Array[AnyRef])]("dateset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.datesetEndValue: AnyRef, 1, Array[AnyRef](null)), "floatset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.floatsetEndValue: AnyRef, 1, Array[AnyRef](null)), "intset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.intsetEndValue: AnyRef, 1, Array[AnyRef](null)), "textset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.textsetEndValue: AnyRef, 1, Array[AnyRef](null)), "tstzset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzsetEndValue: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.AccessorUDFs.tnumberValuespans: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "hasT", 0, "Boolean", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxHast: AnyRef, 1, Array[AnyRef](null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxHast: AnyRef, 1, Array[AnyRef](null))), null)
    injMulti(ext, "hasX", 0, "Boolean", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxHasx: AnyRef, 1, Array[AnyRef](null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxHasx: AnyRef, 1, Array[AnyRef](null))), null)
    injMulti(ext, "lower", 0, "Long", Map[String, (AnyRef, Int, Array[AnyRef])]("bigintspan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.bigintspanLower: AnyRef, 1, Array[AnyRef](null)), "datespan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.datespanLower: AnyRef, 1, Array[AnyRef](null)), "floatspan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.floatspanLower: AnyRef, 1, Array[AnyRef](null)), "intspan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.intspanLower: AnyRef, 1, Array[AnyRef](null)), "intspanset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.intspansetLower: AnyRef, 1, Array[AnyRef](null)), "textset" -> (org.mobilitydb.spark.temporal.TransformUDFs.textsetLower: AnyRef, 1, Array[AnyRef](null)), "tstzspan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzspanLower: AnyRef, 1, Array[AnyRef](null)), "tstzspanset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzspansetLower: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.TTextUDFs.ttextLower: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "minusTime", 1, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("tstzset" -> (org.mobilitydb.spark.temporal.RestrictionUDFs.temporalMinusTstzset: AnyRef, 2, Array[AnyRef](null, null)), "tstzspan" -> (org.mobilitydb.spark.temporal.AccessorUDFs.minusTime: AnyRef, 2, Array[AnyRef](null, null)), "tstzspanset" -> (org.mobilitydb.spark.temporal.RestrictionUDFs.temporalMinusTstzspanset: AnyRef, 2, Array[AnyRef](null, null))), null)
    injMulti(ext, "radians", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("floatset" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatsetRadians: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.MathGapUDFs.radians: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "round", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("floatspanset" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatspansetRound: AnyRef, 2, Array[AnyRef](null, (Integer.valueOf(0): AnyRef))), "stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxRound: AnyRef, 2, Array[AnyRef](null, (Integer.valueOf(0): AnyRef))), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxRound: AnyRef, 2, Array[AnyRef](null, (Integer.valueOf(0): AnyRef)))), null)
    injMulti(ext, "setSRID", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxSetSrid: AnyRef, 2, Array[AnyRef](null, null))), (org.mobilitydb.spark.geo.GeoAnalyticsUDFs.setSRID: AnyRef, 2, Array[AnyRef](null, null)))
    injMulti(ext, "set_distance", 0, "Long", Map[String, (AnyRef, Int, Array[AnyRef])]("bigintset" -> (org.mobilitydb.spark.temporal.SetOpsUDFs.distanceBigintsetBigintset: AnyRef, 2, Array[AnyRef](null, null)), "floatset" -> (org.mobilitydb.spark.temporal.SetOpsUDFs.distanceFloatsetFloatset: AnyRef, 2, Array[AnyRef](null, null)), "intset" -> (org.mobilitydb.spark.temporal.SetOpsUDFs.distanceIntsetIntset: AnyRef, 2, Array[AnyRef](null, null)), "tstzset" -> (org.mobilitydb.spark.temporal.SetOpsUDFs.distanceTstzsetTstzset: AnyRef, 2, Array[AnyRef](null, null))), null)
    injMulti(ext, "shift", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("floatspan" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatspanShiftScale: AnyRef, 3, Array[AnyRef](null, null, null)), "floatspanset" -> (org.mobilitydb.spark.temporal.TransformUDFs.floatspansetShiftScale: AnyRef, 3, Array[AnyRef](null, null, null)), "intspan" -> (org.mobilitydb.spark.temporal.TransformUDFs.intspanShiftScale: AnyRef, 3, Array[AnyRef](null, null, null)), "intspanset" -> (org.mobilitydb.spark.temporal.TransformUDFs.intspansetShiftScale: AnyRef, 3, Array[AnyRef](null, null, null)), "tstzspan" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.tstzspanShiftScale: AnyRef, 3, Array[AnyRef](null, null, null)), "tstzspanset" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.tstzspansetShiftScale: AnyRef, 3, Array[AnyRef](null, null, null))), null)
    injMulti(ext, "shiftTime", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxShiftScaleTime: AnyRef, 3, Array[AnyRef](null, null, null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxShiftScaleTime: AnyRef, 3, Array[AnyRef](null, null, null))), (org.mobilitydb.spark.temporal.AccessorUDFs.shift: AnyRef, 2, Array[AnyRef](null, null)))
    injMulti(ext, "span_distance", 0, "Long", Map[String, (AnyRef, Int, Array[AnyRef])]("bigintspan" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.bigintspanDistance: AnyRef, 2, Array[AnyRef](null, null)), "datespan" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.datespanDistance: AnyRef, 2, Array[AnyRef](null, null)), "floatspan" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.floatspanDistance: AnyRef, 2, Array[AnyRef](null, null)), "floatspanset" -> (org.mobilitydb.spark.temporal.SetSpanGapUDFs.spansetDistance: AnyRef, 2, Array[AnyRef](null, null)), "intspan" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.intspanDistance: AnyRef, 2, Array[AnyRef](null, null)), "tstzspan" -> (org.mobilitydb.spark.temporal.SpanAlgebraUDFs.tstzspanDistance: AnyRef, 2, Array[AnyRef](null, null)), "tstzspanset" -> (org.mobilitydb.spark.temporal.SetSpanGapUDFs.timeDistanceSpanset: AnyRef, 2, Array[AnyRef](null, null))), null)
    injMulti(ext, "startTimestamp", 0, "Timestamp", Map[String, (AnyRef, Int, Array[AnyRef])]("tstzspanset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzspansetStartTimestamptz: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.TemporalUDFs.startTimestamp: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "startValue", 0, "java.sql.Date", Map[String, (AnyRef, Int, Array[AnyRef])]("dateset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.datesetStartValue: AnyRef, 1, Array[AnyRef](null)), "floatset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.floatsetStartValue: AnyRef, 1, Array[AnyRef](null)), "intset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.intsetStartValue: AnyRef, 1, Array[AnyRef](null)), "textset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.textsetStartValue: AnyRef, 1, Array[AnyRef](null)), "tstzset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzsetStartValue: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.AccessorUDFs.tfloatStartValue: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "stbox", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("tstzspan" -> (org.mobilitydb.spark.geo.STBoxUDFs.tstzspanToStbox: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.geo.GeoUDFs.tpointToStbox: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "tbox", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.setToTbox: AnyRef, 1, Array[AnyRef](null)), "timestamptz" -> (org.mobilitydb.spark.temporal.TBoxUDFs.numspanTimestamptzToTbox: AnyRef, 2, Array[AnyRef](null, null))), (org.mobilitydb.spark.temporal.AccessorUDFs.tnumberToTbox: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "timeSpan", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("stbox" -> (org.mobilitydb.spark.geo.STBoxUDFs.stboxToTstzspan: AnyRef, 1, Array[AnyRef](null)), "tbox" -> (org.mobilitydb.spark.temporal.TBoxUDFs.tboxToTstzspan: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.TransformUDFs.temporalToTstzspan: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "timestamps", 0, "String", Map[String, (AnyRef, Int, Array[AnyRef])]("tstzspanset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzspansetNumTimestamps: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.AccessorGapUDFs.atValue: AnyRef, 2, Array[AnyRef](null, null)))
    injMulti(ext, "upper", 0, "Long", Map[String, (AnyRef, Int, Array[AnyRef])]("bigintspan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.bigintspanUpper: AnyRef, 1, Array[AnyRef](null)), "datespan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.datespanUpper: AnyRef, 1, Array[AnyRef](null)), "floatspan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.floatspanUpper: AnyRef, 1, Array[AnyRef](null)), "intspan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.intspanUpper: AnyRef, 1, Array[AnyRef](null)), "intspanset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.intspansetUpper: AnyRef, 1, Array[AnyRef](null)), "textset" -> (org.mobilitydb.spark.temporal.TransformUDFs.textsetUpper: AnyRef, 1, Array[AnyRef](null)), "tstzspan" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzspanUpper: AnyRef, 1, Array[AnyRef](null)), "tstzspanset" -> (org.mobilitydb.spark.temporal.SpanAccessorUDFs.tstzspansetUpper: AnyRef, 1, Array[AnyRef](null))), (org.mobilitydb.spark.temporal.TTextUDFs.ttextUpper: AnyRef, 1, Array[AnyRef](null)))
    injMulti(ext, "width", 0, "Long", Map[String, (AnyRef, Int, Array[AnyRef])]("bigintspan" -> (org.mobilitydb.spark.temporal.AccessorAliasUDFs.bigintspanWidth: AnyRef, 1, Array[AnyRef](null)), "bigintspanset" -> (org.mobilitydb.spark.temporal.AccessorAliasUDFs.bigintspansetWidth: AnyRef, 2, Array[AnyRef](null, (java.lang.Boolean.FALSE: AnyRef))), "floatspan" -> (org.mobilitydb.spark.temporal.AccessorAliasUDFs.floatspanWidth: AnyRef, 1, Array[AnyRef](null)), "floatspanset" -> (org.mobilitydb.spark.temporal.AccessorAliasUDFs.floatspansetWidth: AnyRef, 2, Array[AnyRef](null, (java.lang.Boolean.FALSE: AnyRef))), "intspan" -> (org.mobilitydb.spark.temporal.AccessorAliasUDFs.intspanWidth: AnyRef, 1, Array[AnyRef](null)), "intspanset" -> (org.mobilitydb.spark.temporal.AccessorAliasUDFs.intspansetWidth: AnyRef, 2, Array[AnyRef](null, (java.lang.Boolean.FALSE: AnyRef)))), null)
  }
  // multi-impl not arg0-dispatchable (all impls share arg0 type; need
  // the differentiating arg, e.g. atTime on the time argument):
  //   aDwithin -> ['aDwithin', 'aDwithinGeo']
  //   aIntersects -> ['aIntersects', 'eIntersects']
  //   always_eq -> ['alwaysEqBoolTbool', 'alwaysEqFloatTfloat', 'alwaysEqIntTint', 'alwaysEqTboolBool', 'alwaysEqTemporal', 'alwaysEqTfloatFloat', 'alwaysEqTintInt']
  //   always_ge -> ['alwaysGeFloatTfloat', 'alwaysGeIntTint', 'alwaysGeTemporal', 'alwaysGeTfloatFloat', 'alwaysGeTintInt']
  //   always_gt -> ['alwaysGtFloatTfloat', 'alwaysGtIntTint', 'alwaysGtTemporal', 'alwaysGtTfloatFloat', 'alwaysGtTintInt']
  //   always_le -> ['alwaysLeFloatTfloat', 'alwaysLeIntTint', 'alwaysLeTemporal', 'alwaysLeTfloatFloat', 'alwaysLeTintInt']
  //   always_lt -> ['alwaysLtFloatTfloat', 'alwaysLtIntTint', 'alwaysLtTemporal', 'alwaysLtTfloatFloat', 'alwaysLtTintInt']
  //   always_ne -> ['alwaysNeBoolTbool', 'alwaysNeFloatTfloat', 'alwaysNeIntTint', 'alwaysNeTboolBool', 'alwaysNeTemporal', 'alwaysNeTfloatFloat', 'alwaysNeTintInt']
  //   angularDifference -> ['tnumberAngularDifference', 'tpointAngularDifference']
  //   area -> ['stboxArea', 'stboxPerimeter']
  //   atGeometry -> ['atElevation', 'atGeometry', 'tgeoAtGeom', 'tpointAtElevation']
  //   atValue -> ['tboolAtValue', 'tfloatAtValue', 'tintAtValue', 'tpointAtValue', 'ttextAtValue']
  //   bearing -> ['bearing', 'bearingToPoint']
  //   eDisjoint -> ['eDisjoint', 'eDisjointTgeoTgeo']
  //   eDwithin -> ['eDwithin', 'eDwithinGeo']
  //   endValue -> ['tboolEndValue', 'tfloatEndValue', 'tintEndValue', 'tpointEndValue', 'ttextEndValue']
  //   ever_eq -> ['everEqBoolTbool', 'everEqFloatTfloat', 'everEqIntTint', 'everEqTboolBool', 'everEqTemporal', 'everEqTfloatFloat', 'everEqTintInt']
  //   ever_ge -> ['everGeFloatTfloat', 'everGeIntTint', 'everGeTemporal', 'everGeTfloatFloat', 'everGeTintInt']
  //   ever_gt -> ['everGtFloatTfloat', 'everGtIntTint', 'everGtTemporal', 'everGtTfloatFloat', 'everGtTintInt']
  //   ever_le -> ['everLeFloatTfloat', 'everLeIntTint', 'everLeTemporal', 'everLeTfloatFloat', 'everLeTintInt']
  //   ever_lt -> ['everLtFloatTfloat', 'everLtIntTint', 'everLtTemporal', 'everLtTfloatFloat', 'everLtTintInt']
  //   ever_ne -> ['everNeFloatTfloat', 'everNeIntTint', 'everNeTboolBool', 'everNeTemporal', 'everNeTfloatFloat', 'everNeTintInt']
  //   floatspan -> ['tboxToFloatspan', 'tboxToIntspan']
  //   intspanset -> ['floatToSpanset', 'floatspansetToInt', 'intToSpanset', 'intspanset', 'setToSpanset']
  //   ln -> ['exp', 'ln', 'log10', 'tfloatExp', 'tfloatLn', 'tfloatLog10']
  //   maxValue -> ['tfloatMaxValue', 'tintMaxValue', 'ttextMaxValue']
  //   minValue -> ['tfloatMinValue', 'tintMinValue', 'ttextMinValue']
  //   minusGeometry -> ['tgeoMinusGeom', 'tpointMinusElevation']
  //   minusValue -> ['minusValue', 'tboolMinusValue', 'tfloatMinusValue', 'tintMinusValue', 'tpointMinusValue', 'ttextMinusValue']
  //   scaleValue -> ['tfloatScaleValue', 'tintScaleValue']
  //   set -> ['floatToSet', 'intToSet', 'timestamptzToSet']
  //   shiftScaleValue -> ['tfloatShiftScaleValue', 'tintShiftScaleValue']
  //   shiftValue -> ['tfloatShiftValue', 'tintShiftValue']
  //   span -> ['floatToSpan', 'intToSpan', 'setToSpan', 'spanToSpanset', 'spanset', 'timestamptzToSpan']
  //   span_contained -> ['spanContainedIn', 'spanContainedInSpanset']
  //   span_contains -> ['spanContains', 'spansetContainsSpan']
  //   span_intersection -> ['spanIntersection', 'span_intersection', 'spansetIntersection', 'spansetIntersectionSpan', 'spanset_intersection']
  //   span_minus -> ['spansetMinus', 'spansetMinusSpan', 'spanset_minus']
  //   span_overlaps -> ['spanOverlaps', 'spansetOverlaps']
  //   span_union -> ['spansetUnion', 'spansetUnionSpan', 'spanset_union']
  //   tContains -> ['tContains', 'tContainsTgeoGeo']
  //   tDisjoint -> ['tDisjoint', 'tDisjointTgeoTgeo']
  //   tDistance -> ['tdistanceTfloatFloat', 'tdistanceTgeoGeo', 'tdistanceTgeoTgeo', 'tdistanceTintInt', 'tdistanceTnumberTnumber']
  //   tDwithin -> ['tDwithin', 'tDwithinTgeoGeo']
  //   tIntersects -> ['tIntersects', 'tIntersectsTgeoTgeo']
  //   tTouches -> ['tTouches', 'tTouchesTogeoTgeo']
  //   textset_cat -> ['textsetCat', 'textsetCatTextTextset', 'textsetCatTextsetText']
  //   tint -> ['tboolInst', 'tcbufferInst', 'tfloatInst', 'tfloatToTint', 'tgeompointInst', 'tintInst', 'tposeInst']
  //   tnumber_add -> ['addTfloatFloat', 'addTintInt', 'addTnumberTnumber', 'tnumber_add']
  //   tnumber_div -> ['divTfloatFloat', 'divTnumberTnumber', 'tnumber_div']
  //   tnumber_mul -> ['multTfloatFloat', 'multTintInt', 'multTnumberTnumber', 'tnumber_mul']
  //   tnumber_sub -> ['subTfloatFloat', 'subTintInt', 'subTnumberTnumber', 'tnumber_sub']
  //   valueAtTimestamp -> ['tboolValueAtTimestamptz', 'tfloatValueAtTimestamptz', 'tintValueAtTimestamptz', 'valueAtTimestamp']
  //   valueN -> ['everNeBoolTbool', 'tboolValueN', 'tfloatValueN', 'tintValueN', 'tpointValueN', 'ttextInitcap', 'ttextValueN', 'valueN']
}

object MobilitySparkConnectExtensionsGen {
  private def call(u: AnyRef, m: Int, a: Seq[Any], defaults: Array[AnyRef]): Any = {
    // fill an omitted optional arg with the canonical SQL default, not a null pad
    def g(i: Int): AnyRef =
      if (i < a.length) a(i).asInstanceOf[AnyRef]
      else if (defaults != null && i < defaults.length) defaults(i) else null
    m match {
      case 1 => u.asInstanceOf[UDF1[Any, Any]].call(g(0))
      case 2 => u.asInstanceOf[UDF2[Any, Any, Any]].call(g(0), g(1))
      case 3 => u.asInstanceOf[UDF3[Any, Any, Any, Any]].call(g(0), g(1), g(2))
      case _ => u.asInstanceOf[UDF4[Any, Any, Any, Any, Any]].call(g(0), g(1), g(2), g(3))
    }
  }
  def fn(n: Int, u: AnyRef, m: Int, defaults: Array[AnyRef]): AnyRef = n match {
    case 1 => (a: Any) => call(u, m, Seq(a), defaults)
    case 2 => (a: Any, b: Any) => call(u, m, Seq(a, b), defaults)
    case 3 => (a: Any, b: Any, c: Any) => call(u, m, Seq(a, b, c), defaults)
    case _ => (a: Any, b: Any, c: Any, d: Any) => call(u, m, Seq(a, b, c, d), defaults)
  }
  // route by the differentiating argument's MEOS type-tag name to the matching
  // (impl, impl arity, defaults); the default route handles temporal/unknown tags
  private def pick(args: Seq[Any], dpos: Int, routes: Map[String, (AnyRef, Int, Array[AnyRef])],
                   dflt: (AnyRef, Int, Array[AnyRef])): (AnyRef, Int, Array[AnyRef]) =
    (if (dpos < args.length) args(dpos) else null) match {
      case s: String =>
        val tn = try GeneratedFunctions.meostype_name(GeneratedFunctions.meos_typeof_hexwkb(s))
                 catch { case _: Throwable => null }
        routes.getOrElse(tn, dflt)
      case _ => dflt
    }
  private def run(t: (AnyRef, Int, Array[AnyRef]), a: Seq[Any]): Any =
    if (t == null || t._1 == null) null else call(t._1, t._2, a, t._3)
  def disp(n: Int, dpos: Int, routes: Map[String, (AnyRef, Int, Array[AnyRef])],
           dflt: (AnyRef, Int, Array[AnyRef])): AnyRef = n match {
    case 1 => (a: Any) => run(pick(Seq(a), dpos, routes, dflt), Seq(a))
    case 2 => (a: Any, b: Any) => run(pick(Seq(a, b), dpos, routes, dflt), Seq(a, b))
    case 3 => (a: Any, b: Any, c: Any) => run(pick(Seq(a, b, c), dpos, routes, dflt), Seq(a, b, c))
    case _ => (a: Any, b: Any, c: Any, d: Any) => run(pick(Seq(a, b, c, d), dpos, routes, dflt), Seq(a, b, c, d))
  }
}
