#!/usr/bin/env bash
# regen-from-catalog.sh — regenerate JMEOS (the JVM FFI binding) from the MEOS catalog and
# build the jar the JVM consumers (Spark/Flink/Kafka) bind. The executable form of
# codegen/GENERATION.md.
#
# Usage:  tools/regen-from-catalog.sh <catalog>   (or: CATALOG=<catalog> tools/regen-from-catalog.sh)
#   arg/env CATALOG = meos-idl.json produced by MEOS-API run.py over MobilityDB master (required)
#   env     LIBMEOS = all-families libmeos.so built from master (for tests; optional)
#
# The JVM consumers regenerate their own projections from the same catalog, so the whole JVM
# tier tracks master with no hand-written surface.
set -euo pipefail
CATALOG="${1:-${CATALOG:?set CATALOG (or pass the catalog path) to the meos-idl.json from MEOS-API run.py over MobilityDB master}}"
HERE="$(cd "$(dirname "$0")/.." && pwd)"

# 1. stage the catalog — codegen/input/meos-idl.json is the generator's input. It is derived,
#    not committed, so the directory does not exist in a clean checkout: create it, then
#    overwrite in place (there is no pin and no per-SHA copy).
mkdir -p "$HERE/codegen/input"
cp "$CATALOG" "$HERE/codegen/input/meos-idl.json"

# 2. build the jar the JVM consumers bind. jmeos-core's generate-sources phase runs
#    FunctionsGenerator over the vendored catalog into target/generated-sources/jmeos and adds
#    it as a source root — so the FFI surface is regenerated by the build itself; the script
#    neither invokes the generator directly nor writes anything under src/.
#    With LIBMEOS the FFI suite runs against it (the verified build the orchestrator wants);
#    without it the jar is built with tests skipped at the compile level — the pom pins
#    surefire skipTests=false, so -DskipTests alone would not skip them.
cd "$HERE"
mvn -q -pl codegen -am compile
if [ -n "${LIBMEOS:-}" ]; then
  cp "$LIBMEOS" "$HERE/jmeos-core/src/libmeos.so" 2>/dev/null || true
  GITHUB_WORKFLOW=1 LD_LIBRARY_PATH="$(dirname "$LIBMEOS")${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
    mvn -q -pl jmeos-core -am package
else
  mvn -q -pl jmeos-core -am -Dmaven.test.skip=true package
fi
echo "[jmeos] regenerated from catalog -> $HERE/jar/JMEOS.jar"
