#!/usr/bin/env bash
# regen-from-catalog.sh — regenerate JMEOS (the JVM FFI binding) from the MEOS catalog and
# build the jar the JVM consumers (Spark/Flink/Kafka) bind. The executable form of
# codegen/GENERATION.md.
#
# Usage:  tools/regen-from-catalog.sh <catalog>   (or: CATALOG=<catalog> tools/regen-from-catalog.sh)
#   arg/env CATALOG = meos-idl.json produced by MEOS-API run.py over MobilityDB master (required)
#   env     LIBMEOS = all-families libmeos.so built from master (required: the FFI suite runs against it)
#
# The JVM consumers regenerate their own projections from the same catalog, so the whole JVM
# tier tracks master with no hand-written surface. The generator they do it with is
# `codegen_jvm.py` beside this script — one file with an arm per engine (spark, flink, kafka),
# emitting Java that calls the `functions.GeneratedFunctions` this script produces. It lives
# here because that is the surface it binds: a fold or a widened return in GeneratedFunctions
# changes what the generator must emit, and the two move together. `codegen_spark_udfs.py` is
# beside it too, loaded by the spark arm from the generator's own directory.
set -euo pipefail
CATALOG="${1:-${CATALOG:?set CATALOG (or pass the catalog path) to the meos-idl.json from MEOS-API run.py over MobilityDB master}}"
LIBMEOS="${LIBMEOS:?set LIBMEOS to the all-families libmeos.so; the FFI suite runs against it}"
HERE="$(cd "$(dirname "$0")/.." && pwd)"

# 1. stage the catalog — codegen/input/meos-idl.json is the generator's input. It is derived,
#    not committed, so the directory does not exist in a clean checkout: create it, then
#    overwrite in place (there is no pin and no per-SHA copy).
mkdir -p "$HERE/codegen/input"
cp "$CATALOG" "$HERE/codegen/input/meos-idl.json"

# 2. build the jar the JVM consumers bind. jmeos-core's generate-sources phase runs
#    FunctionsGenerator over the vendored catalog into target/generated-sources/jmeos and adds
#    it as a source root — so the FFI surface is regenerated by the build itself; the script
#    neither invokes the generator directly nor writes anything under src/.
#    The FFI suite runs against LIBMEOS, which is required: a jar built without running it
#    is a jar that compiles, not one whose generated surface answers, and that difference is
#    exactly what a regeneration has to establish.
cd "$HERE"
mvn -q -pl codegen -am compile
cp "$LIBMEOS" "$HERE/jmeos-core/src/libmeos.so" 2>/dev/null || true
rm -rf "$HERE/jmeos-core/target/surefire-reports"
GITHUB_WORKFLOW=1 LD_LIBRARY_PATH="$(dirname "$LIBMEOS")${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
  mvn -q -pl jmeos-core -am package

# 3. assert the suite RAN, which is the only check that does not depend on knowing how it
#    might not have. A surefire flag, a pom that pins one, a lost test directory, a plugin
#    that never binds — each ends the same way, a green build over zero tests. So nothing
#    here guards a particular flag; the count of what surefire recorded is read instead.
RAN=$(find "$HERE/jmeos-core/target/surefire-reports" -name 'TEST-*.xml' 2>/dev/null |
      xargs -r sed -n 's/.*<testsuite[^>]* tests="\([0-9]*\)".*/\1/p' |
      awk '{n += $1} END {print n + 0}')
if [ "${RAN:-0}" -lt 1 ]; then
  echo "regen-from-catalog: the jar built but its suite did not run ($RAN tests)." >&2
  echo "  A jar that compiles is not a jar whose generated surface answers." >&2
  exit 1
fi
echo "[jmeos] FFI suite ran: $RAN tests"
echo "[jmeos] regenerated from catalog -> $HERE/jar/JMEOS.jar"
